In [1]:
### 필요 라이브러리
import os
import pandas as pd
import numpy as np
import datetime as dt
import math
import warnings
warnings.filterwarnings(action='ignore')

### 데이터 보여지는 개수 설정
pd.set_option('display.max_columns', 40)
pd.set_option('display.max_rows', 300)

In [2]:
### 폴더에 존재하는 파일 리스트, 굳이 실행하지 않아도 됨
# path_dir = 'C:/Users/HONGJEONGUI/Desktop/RA/Data/DataOR'
path_dir = '/Data/Data'
 
file_list = os.listdir(path_dir)
print(file_list)

['PT구분코드(전체조회기간).xlsx', 'stktrd_20150102.csv', 'ord201709', 'stkord_20150102.csv.gz', 'ORD_19990104.csv', 'layout_3.csv', '시장정보 데이터 확인 및 요청_레이아웃.xlsx', 'layout_2.csv', '유가 체결장 2단계 샘플.csv', 'layout_1.csv', 'SPOT_TRD_20130102.csv', 'ord', '유가 호가장 2단계 샘플.csv', '코스닥 체결장 2단계 샘플.csv', 'TRD_19990104.csv', '코스닥 호가장 2단계 샘플.csv', 'ksqtrd_20150102.csv']

In [3]:
### 유재인 교수님께서 공유해주신 레이블, 코드 설명 엑셀파일(xlsx)을 (시트가 3개) 각 시트별로 csv로 저장.
### 1번째 위치는 엑셀파일위치, 2,3번째는 코드 저장 위치
sheets = 3
for i in range(1,sheets+1):
    df = pd.read_excel(path_dir+"/시장정보 데이터 확인 및 요청_레이아웃.xlsx", sheet_name=(i-1))
    df.to_csv((path_dir+"/layout_{}.csv").format(i), encoding = "cp949", sep=',', header = False, index = False)
    globals()['layout_{}'.format(i)] = pd.read_csv((path_dir+"/layout_{}.csv").format(i), header = None, encoding="cp949")

In [4]:
df = pd.read_csv(path_dir+"/코스닥 호가장 2단계 샘플.csv",encoding='cp949')

In [5]:
header_df=['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD', '호가장처리가격',
       'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD', 'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC',
       'ASK_STEP1_BSTORD_RQTY', 'ASK_STEP2_BSTORD_PRC','ASK_STEP2_BSTORD_RQTY','ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY','ASK_STEP4_BSTORD_PRC', 'ASK_STEP4_BSTORD_RQTY','ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY',
       'BID_STEP1_BSTORD_PRC', 'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC', 'BID_STEP2_BSTORD_RQTY',
       'BID_STEP3_BSTORD_PRC', 'BID_STEP3_BSTORD_RQTY','BID_STEP4_BSTORD_PRC', 'BID_STEP4_BSTORD_RQTY',
       'BID_STEP5_BSTORD_PRC', 'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD', 'FORNINVST_TP_CD',
       'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량', '매도총호가잔량', '매수총호가잔량',
       '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금', 'AGG_TM', '시가', '고가', '저가',
       'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드', 'MKTSTAT_TP_CD', '매도10단계호가합계잔량',
       '매수10단계호가합계잔량', 'PT_TP_CD']
header = header_df

 
df.columns=header_df
df=df[1:]
df.head()

,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,ORD_COND_CD,INVST_TP_CD,ASK_STEP1_BSTORD_PRC,ASK_STEP1_BSTORD_RQTY,ASK_STEP2_BSTORD_PRC,ASK_STEP2_BSTORD_RQTY,ASK_STEP3_BSTORD_PRC,ASK_STEP3_BSTORD_RQTY,ASK_STEP4_BSTORD_PRC,ASK_STEP4_BSTORD_RQTY,ASK_STEP5_BSTORD_PRC,...,회원사주문시각,예상체결가격,예상체결수량,매도총호가잔량,매수총호가잔량,호가체결접수순서번호,직전체결가격,누적체결수량,누적거래대금,AGG_TM,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD
1,KR7009620006,20171030,23650,1,0,19550,2,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125949640,0,0,21901,29871,34709,19550,0,0,0,15350,19850,14400,0,2,0,40,4465,4210,0
2,KR7009620006,20171030,23651,1,0,19500,1,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125949734,0,0,21901,29871,34710,19550,77,1505350,125949735,15350,19850,14400,0,2,0,40,4465,4210,0
3,KR7009620006,20171030,23652,1,0,19550,1,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125950114,0,0,21901,29794,34712,19550,5,97750,125950115,15350,19850,14400,0,2,0,40,4465,4133,0
4,KR7009620006,20171030,23653,1,0,19250,2,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125950375,0,0,21901,29919,34714,19550,130,2502500,130058726,15350,19850,14400,0,2,0,40,4465,4258,0
5,KR7009620006,20171030,23654,1,0,19600,2,2,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125950687,0,0,21901,29919,34715,19550,0,0,0,15350,19850,14400,23599,2,0,40,4465,3432,0

In [6]:
data_dir=path_dir+'/'+'ord'

UUID_count={}
file_list = os.listdir(data_dir)
print(file_list)
columnlist=['MBR_NO','BRN_NO']
filecount=0
for filename in file_list:
    print(filename)
    df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
    if 'SPOT' in filename:
        df1.columns = list(layout_1.iloc[0:len(df1.iloc[0])][0])
        print("Using 2013 data")
    else:
        continue
    if(filecount==0):
        countdf=df1.groupby(columnlist).size()
    else:
        countdf=countdf.add(df1.groupby(columnlist).size())
    filecount+=1
    break

['SPOT_ORD_20130102.csv', 'ksqord_20150102.csv']
SPOT_ORD_20130102.csv
Using 2013 data

In [7]:
data_dir=path_dir+'/'+'ord201709'

UUID_count={}
file_list = os.listdir(data_dir)
print(file_list)
columnlist=['MBR_NO','BRN_NO']
columnISU=['ISU_CD']
filecount=0
for filename in file_list:
    print(filename)
    df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
    if 'SPOT' in filename:
        df1.columns = list(layout_1.iloc[0:len(df1.iloc[0])][0])
        print("Using 2013 data")
    elif 'ksqord' in filename:

        df1.columns= header_df
        print("Using 2017 data")
    if(filecount==0):
        countdf=df1.groupby(columnlist).size()#####기관별 거래
        countdf2=df1.groupby(columnISU).size()######종목별 거래
    else:
        countdf=countdf.add(df1.groupby(columnlist).size())
        countdf2=countdf2.add(df1.groupby(columnISU).size())
    filecount+=1
    break

['ksqord_20170904.csv', 'ksqord_20170905.csv', 'ksqord_20170929.csv', 'ksqord_20170926.csv', 'ksqord_20170913.csv', 'ksqord_20170928.csv', 'ksqord_20170901.csv', 'ksqord_20170918.csv', 'ksqord_20170922.csv', 'ksqord_20170906.csv', 'ksqord_20170919.csv', 'ksqord_20170921.csv', 'ksqord_20170920.csv', 'ksqord_20170925.csv', 'ksqord_20170908.csv', 'ksqord_20170915.csv', 'ksqord_20170907.csv', 'ksqord_20170914.csv', 'ksqord_20170927.csv', 'ksqord_20170911.csv', 'ksqord_20170912.csv']
ksqord_20170904.csv
Using 2017 data

In [8]:
max_MBR_NO,max_BRN_NO=countdf.idxmax()
ISU_CD=countdf2.idxmax()

In [9]:
ISU_CD='KR7068270008'

In [10]:
MBR_NO,BRN_NO=max_MBR_NO,max_BRN_NO

print(max_MBR_NO,max_BRN_NO,ISU_CD)
#36 1 KR7068270008

위에서 구한 종목과 기관 데이터 가지고 오기

data_dir=path_dir+'/'+'ord'

UUID_count={}
file_list = os.listdir(data_dir)
print(file_list)
columnlist=['MBR_NO','BRN_NO']
filecount=0
for filename in file_list:
    print(filename)
    df2013 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
    if 'SPOT' in filename:
        df2013.columns = list(layout_1.iloc[0:len(df1.iloc[0])][0])[:len(df2013.columns)]
        print("Using 2013 data")
    else:
        continue
    filecount+=1
    break

df2013[df2013['MBR_NO']==MBR_NO][['MKTPARTC_KOR_ABBRV','BRN_NM']].value_count

df2013[(df2013['MBR_NO']==MBR_NO)& (df2013['BRN_NO']==BRN_NO)][['MKTPARTC_KOR_ABBRV','BRN_NM']].head()

In [14]:
data_dir=path_dir+'/'+'ord201709'

UUID_count={}
file_list = os.listdir(data_dir)
print(file_list)
filecount=0
for filename in file_list:
    print(filename)
    if 'ksqord_2017090' not in filename:
        continue
    df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
    if 'SPOT' in filename:
        continue
        df1.columns = list(layout_1.iloc[0:len(df1.iloc[0])][0])
        print("Using 2013 data")
    elif 'ksqord_2017090' in filename:
        df1.columns= header_df
        df=df[1:]
        print("Using 2017 data")
    else:
        continue
#    df1=df1.set_index(['ORD_DD','ORD_ACPT_TM'])
    if(filecount==0):
        dfmost=df1[(df1['MBR_NO']==max_MBR_NO) & (df1['BRN_NO']==max_BRN_NO)]
        dftotISU=df1[df1['ISU_CD']==ISU_CD]
    else:
        dfmost=pd.concat([dfmost,df1[(df1['MBR_NO']==max_MBR_NO) & (df1['BRN_NO']==max_BRN_NO)],])
        dftotISU=pd.concat([dftotISU,df1[df1['ISU_CD']==ISU_CD],])
#         dfmost.join(df1[(df1['MBR_NO']==max_MBR_NO) & (df1['BRN_NO']==max_BRN_NO)],how='outer')
    filecount+=1

['ksqord_20170904.csv', 'ksqord_20170905.csv', 'ksqord_20170929.csv', 'ksqord_20170926.csv', 'ksqord_20170913.csv', 'ksqord_20170928.csv', 'ksqord_20170901.csv', 'ksqord_20170918.csv', 'ksqord_20170922.csv', 'ksqord_20170906.csv', 'ksqord_20170919.csv', 'ksqord_20170921.csv', 'ksqord_20170920.csv', 'ksqord_20170925.csv', 'ksqord_20170908.csv', 'ksqord_20170915.csv', 'ksqord_20170907.csv', 'ksqord_20170914.csv', 'ksqord_20170927.csv', 'ksqord_20170911.csv', 'ksqord_20170912.csv']
ksqord_20170904.csv
Using 2017 data
ksqord_20170905.csv
Using 2017 data
ksqord_20170929.csv
ksqord_20170926.csv
ksqord_20170913.csv
ksqord_20170928.csv
ksqord_20170901.csv
Using 2017 data
ksqord_20170918.csv
ksqord_20170922.csv
ksqord_20170906.csv
Using 2017 data
ksqord_20170919.csv
ksqord_20170921.csv
ksqord_20170920.csv
ksqord_20170925.csv
ksqord_20170908.csv
Using 2017 data
ksqord_20170915.csv
ksqord_20170907.csv
Using 2017 data
ksqord_20170914.csv
ksqord_20170927.csv
ksqord_20170911.csv
ksqord_20170912.csv

In [15]:
dfmostkor = dfmost[dfmost['ISU_CD'].str.contains('KR')]

In [16]:
dfmostkor.sort_values(by=['ORD_DD','ISU_CD','ORD_ACPT_TM'])
# dfmost.sort_values(by='ORD_DD')

,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,ORD_COND_CD,INVST_TP_CD,ASK_STEP1_BSTORD_PRC,ASK_STEP1_BSTORD_RQTY,ASK_STEP2_BSTORD_PRC,ASK_STEP2_BSTORD_RQTY,ASK_STEP3_BSTORD_PRC,ASK_STEP3_BSTORD_RQTY,ASK_STEP4_BSTORD_PRC,ASK_STEP4_BSTORD_RQTY,ASK_STEP5_BSTORD_PRC,...,회원사주문시각,예상체결가격,예상체결수량,매도총호가잔량,매수총호가잔량,호가체결접수순서번호,직전체결가격,누적체결수량,누적거래대금,AGG_TM,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD
83236,KR7000250001,20170901,3645,1,0,13450,1,1,2,0,1000,13400,66,13450,3811,13500,4002,13550,4243,13600,...,121401977,0,0,152309,71751,4987,13400,0,0,0,12950,13650,12950,0,2,0,40,47871,40231,0
83273,KR7000250001,20170901,3681,1,0,13450,1,3,2,0,1000,13450,3456,13500,4058,13550,4243,13600,6455,13650,...,121700186,0,0,151944,72988,5035,13450,0,0,0,12950,13650,12950,3645,2,0,40,54179,39733,0
83283,KR7000250001,20170901,3691,1,0,13450,1,1,2,0,1000,13450,3966,13500,4109,13550,4243,13600,6455,13650,...,122102151,0,0,152505,71244,5046,13400,0,0,0,12950,13650,12950,0,2,0,40,54740,37992,0
83309,KR7000250001,20170901,3717,1,0,13500,1,1,2,0,1000,13450,6089,13500,4579,13550,5020,13600,5928,13650,...,122802102,0,0,155350,72309,5081,13450,0,0,0,12950,13650,12950,0,2,0,40,57585,39157,0
83390,KR7000250001,20170901,3798,1,0,13450,1,3,2,0,1000,13450,5769,13500,5455,13550,4244,13600,5728,13650,...,124100207,0,0,158332,74615,5191,13400,0,0,0,12950,13650,12950,3691,2,0,40,60566,41962,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8403861,KR7272290008,20170908,13271,1,0,75800,1,3,2,0,1000,75600,50,75700,20,75800,1063,0,0,0,...,153002454,75600,2987,74801,24498,20189,75800,0,0,0,76200,77300,75500,13092,2,0,30,1133,8842,0
8403862,KR7272290008,20170908,13272,1,0,75800,1,3,2,0,1000,75600,50,75700,20,75800,1052,0,0,0,...,153005621,75600,2987,74790,24498,20190,75800,0,0,0,76200,77300,75500,13086,2,0,30,1122,8842,0
8403863,KR7272290008,20170908,13273,1,0,75800,1,3,2,0,1000,75600,50,75700,20,75800,1027,0,0,0,...,153005670,75600,2987,74765,24498,20191,75800,0,0,0,76200,77300,75500,13090,2,0,30,1097,8842,0
8403864,KR7272290008,20170908,13274,1,0,75800,1,3,2,0,1000,75600,50,75700,20,75800,1025,0,0,0,...,153005814,75600,2987,74763,24498,20192,75800,0,0,0,76200,77300,75500,13089,2,0,30,1095,8842,0
8403865,KR7272290008,20170908,13275,1,0,75800,1,3,2,0,1000,75600,50,75700,20,75800,993,0,0,0,...,153005834,75600,2987,74731,24498,20193,75800,0,0,0,76200,77300,75500,13087,2,0,30,1063,8842,0

dfmostkor.to_csv('KR2017090.csv',encoding="cp949")

In [17]:
dfmostkor['hourmin']=dfmostkor['ORD_ACPT_TM']//1000

In [18]:
dfmostkor.groupby(['ISU_CD']).size()

ISU_CD
KR7000250001    6547
KR7001000009     289
KR7001540004    1751
KR7001840008    1588
KR7002230001    4826
                ...
KR7264450008    1206
KR7265520007    7763
KR7267980001     704
KR7272290008    2532
KR8392070007      41
Length: 944, dtype: int64

In [19]:
len(dfmostkor)

2778246

In [20]:
ISU_CD=dfmostkor.groupby(['ISU_CD']).size().idxmax()
print(ISU_CD)
print(dfmostkor.groupby(['ISU_CD']).size().max())
print(dfmostkor.groupby(['ISU_CD']).size().sum())

KR7068270008
36528
2778246

In [21]:
dfmostkor.columns

Index(['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD',
       '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC', 'ASK_STEP1_BSTORD_RQTY',
       'ASK_STEP2_BSTORD_PRC', 'ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_PRC',
       'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY', 'BID_STEP1_BSTORD_PRC',
       'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC',
       'BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_PRC',
       'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_PRC',
       'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_PRC',
       'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD',
       'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금',
       'AGG_TM', '시가', '고가', '저가', 'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드',
       'MKTSTAT_TP_CD', '매도10단계호가합계잔량', '매수10단계호가합계잔량', 'PT_TP_CD', 'hourmin'],
      dtype='object')

In [22]:
#dfISU=dfmostkor[dfmostkor['ISU_CD']==ISU_CD]
dfISU=dfmostkor

In [23]:
dfISU['hourmin']=dfISU['ORD_ACPT_TM']//1000000

In [24]:
dfISU.columns

Index(['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD',
       '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC', 'ASK_STEP1_BSTORD_RQTY',
       'ASK_STEP2_BSTORD_PRC', 'ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_PRC',
       'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY', 'BID_STEP1_BSTORD_PRC',
       'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC',
       'BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_PRC',
       'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_PRC',
       'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_PRC',
       'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD',
       'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금',
       'AGG_TM', '시가', '고가', '저가', 'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드',
       'MKTSTAT_TP_CD', '매도10단계호가합계잔량', '매수10단계호가합계잔량', 'PT_TP_CD', 'hourmin'],
      dtype='object')

In [25]:
clist=['PT_TP_CD']
dfISU[clist].groupby(clist).size()

PT_TP_CD
0     1687370
31    1090876
dtype: int64

In [26]:
columns=['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD',
       '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC', 'ASK_STEP1_BSTORD_RQTY',
       'ASK_STEP2_BSTORD_PRC', 'ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_PRC',
       'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY', 'BID_STEP1_BSTORD_PRC',
       'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC',
       'BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_PRC',
       'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_PRC',
       'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_PRC',
       'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD',
       'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금',
       'AGG_TM', '시가', '고가', '저가', 'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드',
       'MKTSTAT_TP_CD', '매도10단계호가합계잔량', '매수10단계호가합계잔량', 'PT_TP_CD', 'hourmin']
columns=['호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 
         'ORD_QTY', 'ORD_PRC', '매도총호가잔량',
       '매수총호가잔량', '직전체결가격', '누적체결수량', '누적거래대금', '시가', '고가', '저가',
        'hourmin']
columns= [ '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
        'CNTR_CD', 'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '직전체결가격', '누적체결수량', '누적거래대금',
         '시가', '고가', '저가',  'MKTSTAT_TP_CD', 'hourmin']
columns= [ '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_QTY', 'ORD_PRC',
       '매도총호가잔량', '매수총호가잔량', '직전체결가격', 
         '시가', '고가', '저가',  'MKTSTAT_TP_CD', 'hourmin']

columns=['ISU_CD','ORD_DD','ASKBID_TP_CD', 'MODCANCL_TP_CD',  'ASK_STEP1_BSTORD_PRC','BID_STEP1_BSTORD_PRC',
         'ORD_QTY', 'ORD_PRC', '매도총호가잔량',
       '매수총호가잔량',  '시가', '고가', '저가','hourmin']

In [27]:
columns

['ISU_CD',
 'ORD_DD',
 'ASKBID_TP_CD',
 'MODCANCL_TP_CD',
 'ASK_STEP1_BSTORD_PRC',
 'BID_STEP1_BSTORD_PRC',
 'ORD_QTY',
 'ORD_PRC',
 '매도총호가잔량',
 '매수총호가잔량',
 '시가',
 '고가',
 '저가',
 'hourmin']

In [28]:
Pdf=dfISU[columns]

In [29]:
dfISU['시가']

61570      13000
61571      13000
61572      13000
61573      13000
61574      13000
           ...
7649860    73200
7651054    73200
7651099    73200
7651100    73200
7651924    73200
Name: 시가, Length: 2778246, dtype: int64

In [30]:
Pdf=Pdf[Pdf['ORD_PRC']!=0]
Pdf=Pdf[Pdf['MODCANCL_TP_CD']==1]
Pdf['시가']=(Pdf['ASK_STEP1_BSTORD_PRC']+Pdf['BID_STEP1_BSTORD_PRC'])/2
Pdf['count']=1
Pdf['High']=(Pdf['고가']-Pdf['시가'])/Pdf['시가']
Pdf['Low']=(Pdf['저가']-Pdf['시가'])/Pdf['시가']
Pdf['ORD_NET']=Pdf['ORD_PRC']*Pdf['ORD_QTY']
PdfA=Pdf[Pdf['ASKBID_TP_CD']==1]
PdfB=Pdf[Pdf['ASKBID_TP_CD']==2]

In [31]:
newcolumns=['ISU_CD','ORD_DD','hourmin','시가','ORD_QTY','ORD_NET',  'High','Low','매도총호가잔량',
       '매수총호가잔량','count']
PdfA=PdfA[newcolumns]
PdfB=PdfB[newcolumns]

In [32]:
PdfAA=PdfA.groupby(['ISU_CD','ORD_DD','hourmin']).sum()
#PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']=PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']/PdfAA['count']
PdfAA['시가']=PdfAA['시가']/PdfAA['count']
PdfAA['High']=PdfAA['High']/PdfAA['count']
PdfAA['Low']=PdfAA['Low']/PdfAA['count']
PdfAA['매도총호가잔량']=PdfAA['매도총호가잔량']/PdfAA['count']
PdfAA['매수총호가잔량']=PdfAA['매수총호가잔량']/PdfAA['count']
PdfAA['ORD_PRC_REL']=PdfAA['ORD_NET']/PdfAA['ORD_QTY']/PdfAA['시가']
PdfBB=PdfB.groupby(['ISU_CD','ORD_DD','hourmin']).sum()
#PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']=PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']/PdfAA['count']
PdfBB['시가']=PdfBB['시가']/PdfBB['count']
PdfBB['High']=PdfBB['High']/PdfBB['count']
PdfBB['Low']=PdfBB['Low']/PdfBB['count']
PdfBB['매도총호가잔량']=PdfBB['매도총호가잔량']/PdfBB['count']
PdfBB['매수총호가잔량']=PdfBB['매수총호가잔량']/PdfBB['count']
PdfBB['ORD_PRC_REL']=PdfBB['ORD_NET']/PdfBB['ORD_QTY']/PdfBB['시가']

In [33]:
PdfAA

                                         시가  ORD_QTY   ORD_NET      High  \
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 121      13375.000000      440   5918000  0.020561
                      122      13425.000000      980  13204500  0.016760
                      140      13550.000000     1010  13760500  0.007384
                      141      13525.000000      160   2160000  0.009242
                      142      13525.000000      370   5013500  0.009242
...                                     ...      ...       ...       ...
KR7272290008 20170908 150      75782.954545      312  23666600  0.020020
                      151      75650.000000       21   1589700  0.021811
                      152      75550.000000      101   7655800  0.023163
KR8392070007 20170904 132       6360.000000       44    280370  0.026730
                      133       6359.761905     1050   6694500  0.026780

                                    Low        매도총호가잔량        매수총호가잔량  count  \
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 121     -0.031776  152309.000000   71751.000000      1
                      122     -0.035382  153927.500000   71776.500000      2
                      140     -0.044277  130582.500000  109696.000000      2
                      141     -0.042514  143899.000000   93958.000000      1
                      142     -0.042514  145577.000000  110557.000000      1
...                                 ...            ...            ...    ...
KR7272290008 20170908 150     -0.003732   76409.681818   21762.840909     44
                      151     -0.001983   74835.000000   20850.500000      8
                      152     -0.000662   74957.250000   22766.000000      8
KR8392070007 20170904 132     -0.015723   63939.500000   52518.000000      2
                      133     -0.015675   64937.809524   52608.714286     21

                               ORD_PRC_REL
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 121         1.005607
                      122         1.003648
                      140         1.005480
                      141         0.998152
                      142         1.001848
...                                    ...
KR7272290008 20170908 150         1.000944
                      151         1.000661
                      152         1.003309
KR8392070007 20170904 132         1.001894
                      133         1.002508

[51223 rows x 9 columns]

In [34]:
PdfBB

                                    시가  ORD_QTY   ORD_NET      High       Low  \
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 151      13425.0     1630  21597500  0.016760 -0.035382
             20170904 151      13025.0     1630  20945500  0.024952 -0.001919
             20170905 113      12775.0      185   2331000  0.033268 -0.001957
                      151      12775.0     1637  20626200  0.033268 -0.013699
             20170906 90       12665.0      353   4438000  0.006727  0.001179
...                                ...      ...       ...       ...       ...
KR7272290008 20170907 151      76100.0     1184  88326400  0.002628 -0.049934
KR8392070007 20170901 92        6395.0       43    274770  0.010164 -0.013292
             20170904 91        6330.0       14     88900  0.017378 -0.011058
                      113       6415.0       14     89880  0.017927 -0.024162
                      122       6365.0       15     95550  0.025923 -0.016496

                                     매도총호가잔량  매수총호가잔량  count  ORD_PRC_REL
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 151      165735.000000  74133.0      1     0.986965
             20170904 151       89064.000000  70999.0      1     0.986564
             20170905 113       95943.000000  39453.0      1     0.986301
                      151       99637.000000  60701.0      1     0.986301
             20170906 90        62266.066667  29608.2     15     0.992676
...                                      ...      ...    ...          ...
KR7272290008 20170907 151       35063.000000  48605.0      1     0.980289
KR8392070007 20170901 92       186377.000000  19316.0      1     0.999218
             20170904 91        48744.000000  48088.0      1     1.003160
                      113       55408.000000  57182.0      1     1.000779
                      122       56398.000000  55058.0      1     1.000786

[51045 rows x 9 columns]

In [35]:
dfmostkor

,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,ORD_COND_CD,INVST_TP_CD,ASK_STEP1_BSTORD_PRC,ASK_STEP1_BSTORD_RQTY,ASK_STEP2_BSTORD_PRC,ASK_STEP2_BSTORD_RQTY,ASK_STEP3_BSTORD_PRC,ASK_STEP3_BSTORD_RQTY,ASK_STEP4_BSTORD_PRC,ASK_STEP4_BSTORD_RQTY,ASK_STEP5_BSTORD_PRC,...,예상체결가격,예상체결수량,매도총호가잔량,매수총호가잔량,호가체결접수순서번호,직전체결가격,누적체결수량,누적거래대금,AGG_TM,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD,hourmin
61570,KR7000250001,20170904,552,1,0,13150,1,1,2,0,1000,13100,1060,13150,2077,13200,4125,13250,2888,13300,...,0,0,57531,68177,654,13100,0,0,0,13000,13100,13000,0,2,0,40,15263,31817,0,90
61571,KR7000250001,20170904,553,1,0,13150,1,1,2,0,1000,13100,1060,13150,2079,13200,4125,13250,2888,13300,...,0,0,57533,68177,655,13100,0,0,0,13000,13100,13000,0,2,0,40,15265,31817,0,90
61572,KR7000250001,20170904,554,1,0,13150,1,1,2,0,1000,13100,1060,13150,2081,13200,4125,13250,2888,13300,...,0,0,57535,68177,656,13100,0,0,0,13000,13100,13000,0,2,0,40,15267,31817,0,90
61573,KR7000250001,20170904,555,1,0,13150,1,1,2,0,1000,13100,1060,13150,2082,13200,4125,13250,2888,13300,...,0,0,57536,68177,657,13100,0,0,0,13000,13100,13000,0,2,0,40,15268,31817,0,90
61574,KR7000250001,20170904,556,1,0,13150,1,1,2,0,1000,13100,1060,13150,2084,13200,4125,13250,2888,13300,...,0,0,57538,68177,658,13100,0,0,0,13000,13100,13000,0,2,0,40,15270,31817,0,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7649860,KR7272290008,20170907,12962,1,0,75700,2,1,2,0,1000,75800,498,75900,2295,76000,12197,76100,1158,76200,...,0,0,45794,50552,20781,75800,106,8024200,143344849,73200,76000,72300,0,2,0,40,20735,7829,0,143
7651054,KR7272290008,20170907,14156,1,0,75800,2,1,2,0,1000,75900,683,76000,10951,76100,1119,76200,236,76300,...,0,0,43443,43654,22879,75800,0,0,0,73200,76000,72300,0,2,0,40,20493,5848,0,150
7651099,KR7272290008,20170907,14201,1,0,75800,2,3,2,0,1000,76000,9941,76100,1119,76200,236,76300,457,76400,...,0,0,41699,45480,22948,76000,0,0,0,73200,76000,72300,14156,2,0,40,20080,7295,0,150
7651100,KR7272290008,20170907,14202,1,0,75900,2,1,2,0,1000,76000,9941,76100,1119,76200,236,76300,457,76400,...,0,0,41699,45511,22949,76000,31,2352900,150410444,73200,76000,72300,0,2,0,40,20080,7326,0,150
7651924,KR7272290008,20170907,15026,1,0,74600,2,1,2,0,1000,76200,1323,76300,1686,76400,1959,76500,2918,76600,...,0,0,35063,48605,24431,76000,0,0,0,73200,76300,72300,0,2,0,40,16300,11160,0,151

In [36]:
# dftotISU['hourmin']=dftotISU['ORD_ACPT_TM']//1000000
# dftotISU['시가']=(dftotISU['ASK_STEP1_BSTORD_PRC']+dftotISU['BID_STEP1_BSTORD_PRC'])/2
# dftotISU['High']=(dftotISU['고가']-dftotISU['시가'])/dftotISU['시가']
# dftotISU['Low']=(dftotISU['저가']-dftotISU['시가'])/dftotISU['시가']
# dftotISU['count']=1

dfmostkor['hourmin']=dfmostkor['ORD_ACPT_TM']//1000000
dfmostkor['시가']=(dfmostkor['ASK_STEP1_BSTORD_PRC']+dfmostkor['BID_STEP1_BSTORD_PRC'])/2
dfmostkor['High']=(dfmostkor['고가']-dfmostkor['시가'])/dfmostkor['시가']
dfmostkor['Low']=(dfmostkor['저가']-dfmostkor['시가'])/dfmostkor['시가']
dfmostkor['count']=1

dftot=dfmostkor.groupby(['ISU_CD','ORD_DD','hourmin']).sum()
#PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']=PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']/PdfAA['count']
dftot['시가']=dftot['시가']/dftot['count']
dftot['High']=dftot['High']/dftot['count']
dftot['Low']=dftot['Low']/dftot['count']
dftot['매도총호가잔량']=dftot['매도총호가잔량']/dftot['count']
dftot['매수총호가잔량']=dftot['매수총호가잔량']/dftot['count']

dftot=dftot[['시가','High','Low','매도총호가잔량',
       '매수총호가잔량']]

In [37]:
dftot

                                         시가      High       Low  \
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 121      13400.000000  0.018660 -0.033579
                      122      13425.000000  0.016760 -0.035382
                      124      13425.000000  0.016760 -0.035382
                      140      13512.500000  0.010185 -0.041619
                      141      13525.000000  0.009242 -0.042514
...                                     ...       ...       ...
KR8392070007 20170904 91        6330.000000  0.017378 -0.011058
                      113       6415.000000  0.017927 -0.024162
                      122       6365.000000  0.025923 -0.016496
                      132       6360.000000  0.026730 -0.015723
                      133       6363.571429  0.026169 -0.016260

                                     매도총호가잔량       매수총호가잔량
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 121      152126.500000  72369.500000
                      122      153927.500000  71776.500000
                      124      158097.000000  74615.000000
                      140      135106.750000  98324.000000
                      141      143899.000000  93958.000000
...                                      ...           ...
KR8392070007 20170904 91        48744.000000  48088.000000
                      113       55408.000000  57182.000000
                      122       56398.000000  55058.000000
                      132       63939.500000  52518.000000
                      133       65339.857143  52792.457143

[89469 rows x 5 columns]

In [38]:
X=dftot[['시가','High','Low','매도총호가잔량','매수총호가잔량']]
X=X.reset_index()
X=X[(X['ORD_DD']<20170908)&(X['hourmin']<153)&(X['hourmin']>86)]
Y=PdfAA.add(-1*PdfBB,fill_value=0)['ORD_QTY']

In [39]:
ISU_CD_list=(X.groupby(['ISU_CD']).count().reset_index())['ISU_CD'].to_list()

In [40]:
ISU_CD_list

['KR7000250001',
 'KR7001000009',
 'KR7001540004',
 'KR7001840008',
 'KR7002230001',
 'KR7002290005',
 'KR7002800001',
 'KR7003100005',
 'KR7003310000',
 'KR7003380003',
 'KR7003670007',
 'KR7004650008',
 'KR7004780003',
 'KR7005160007',
 'KR7005290002',
 'KR7005860002',
 'KR7005990007',
 'KR7006050009',
 'KR7006730006',
 'KR7006910004',
 'KR7006920003',
 'KR7007390008',
 'KR7007530009',
 'KR7007720006',
 'KR7007820004',
 'KR7008470007',
 'KR7008800005',
 'KR7009300005',
 'KR7009730003',
 'KR7009780008',
 'KR7010170009',
 'KR7010240000',
 'KR7010280006',
 'KR7010470003',
 'KR7011040003',
 'KR7011080009',
 'KR7011320009',
 'KR7011370004',
 'KR7011560000',
 'KR7012340006',
 'KR7012700001',
 'KR7012790002',
 'KR7012860003',
 'KR7013030002',
 'KR7013120001',
 'KR7013310008',
 'KR7013720008',
 'KR7013810007',
 'KR7013990007',
 'KR7014100002',
 'KR7014200000',
 'KR7014470009',
 'KR7014570006',
 'KR7014620009',
 'KR7015710007',
 'KR7015750003',
 'KR7016100000',
 'KR7016170003',
 'KR7016250003',
 'KR7016600009',
 'KR7016670002',
 'KR7017000001',
 'KR7017250002',
 'KR7017480005',
 'KR7017510009',
 'KR7017650003',
 'KR7017890005',
 'KR7018000000',
 'KR7018310003',
 'KR7018680009',
 'KR7018700005',
 'KR7019210004',
 'KR7019550003',
 'KR7019570001',
 'KR7019590009',
 'KR7019660000',
 'KR7019770007',
 'KR7019990001',
 'KR7020180006',
 'KR7020710000',
 'KR7021040001',
 'KR7021080007',
 'KR7021320007',
 'KR7021650007',
 'KR7022100002',
 'KR7022220008',
 'KR7023160005',
 'KR7023410004',
 'KR7023440001',
 'KR7023460009',
 'KR7023600000',
 'KR7023760002',
 'KR7023890007',
 'KR7023910003',
 'KR7024120008',
 'KR7024660003',
 'KR7024800005',
 'KR7024810004',
 'KR7024830002',
 'KR7024840001',
 'KR7024850000',
 'KR7024910002',
 'KR7024950008',
 'KR7025320003',
 'KR7025440009',
 'KR7025550005',
 'KR7025770009',
 'KR7025900002',
 'KR7025950007',
 'KR7025980004',
 'KR7026150003',
 'KR7026180000',
 'KR7026260000',
 'KR7026910000',
 'KR7027050004',
 'KR7027580000',
 'KR7027710003',
 'KR7027830009',
 'KR7028040004',
 'KR7028150001',
 'KR7028300002',
 'KR7029960002',
 'KR7030190003',
 'KR7030270003',
 'KR7030520001',
 'KR7030530000',
 'KR7030960009',
 'KR7031310006',
 'KR7031330004',
 'KR7031390008',
 'KR7031510001',
 'KR7031860000',
 'KR7031980006',
 'KR7032080004',
 'KR7032190001',
 'KR7032280000',
 'KR7032500001',
 'KR7032540007',
 'KR7032580003',
 'KR7032620007',
 'KR7032680001',
 'KR7032750002',
 'KR7032790008',
 'KR7032800005',
 'KR7032820003',
 'KR7032850000',
 'KR7032940009',
 'KR7032980005',
 'KR7033050006',
 'KR7033100009',
 'KR7033110008',
 'KR7033130006',
 'KR7033160003',
 'KR7033170002',
 'KR7033290008',
 'KR7033320003',
 'KR7033340001',
 'KR7033500000',
 'KR7033540006',
 'KR7033560004',
 'KR7033600008',
 'KR7033640004',
 'KR7033790007',
 'KR7034230003',
 'KR7034940007',
 'KR7035080001',
 'KR7035200005',
 'KR7035460005',
 'KR7035480003',
 'KR7035600006',
 'KR7035610005',
 'KR7035620004',
 'KR7035760008',
 'KR7035810001',
 'KR7035890003',
 'KR7035900000',
 'KR7036000008',
 'KR7036010007',
 'KR7036030005',
 'KR7036090009',
 'KR7036120004',
 'KR7036170009',
 'KR7036190007',
 'KR7036200004',
 'KR7036260008',
 'KR7036420008',
 'KR7036490001',
 'KR7036540003',
 'KR7036560001',
 'KR7036620003',
 'KR7036630002',
 'KR7036640001',
 'KR7036690006',
 'KR7036710002',
 'KR7036800001',
 'KR7036810000',
 'KR7036830008',
 'KR7036890002',
 'KR7036930006',
 'KR7037070000',
 'KR7037230000',
 'KR7037330008',
 'KR7037350006',
 'KR7037370004',
 'KR7037400009',
 'KR7037440005',
 'KR7037460003',
 'KR7037760006',
 'KR7037950003',
 'KR7038060000',
 'KR7038070009',
 'KR7038160008',
 'KR7038290003',
 'KR7038460002',
 'KR7038530002',
 'KR7038540001',
 'KR7038620001',
 'KR7038680005',
 'KR7038870002',
 'KR7038880001',
 'KR7039010004',
 'KR7039030002',
 'KR7039200001',
 'KR7039230008',
 'KR7039240007',
 'KR7039290002',
 'KR7039310008',
 'KR7039340005',
 'KR7039420005',
 'KR7039440003',
 'KR7039560008',
 'KR7039830005',
 'KR7039840004',
 'KR7039980008',
 'KR7040160004',
 'KR7040350001',
 'KR7040420002',
 'KR7040610008',
 'KR7040910002',
 'KR7041020009',
 'KR7041140005',
 'KR7041190000',
 'KR7041440009',
 'KR7041460007',
 'KR7041510009',
 'KR7041520008',
 'KR7041590001',
 'KR7041830001',
 'KR7041910001',
 'KR7041920000',
 'KR7041960006',
 'KR7042040006',
 'KR7042370007',
 'KR7042420000',
 'KR7042500009',
 'KR7042520007',
 'KR7042940007',
 'KR7043090000',
 'KR7043100007',
 'KR7043150002',
 'KR7043200005',
 'KR7043260009',
 'KR7043340009',
 'KR7043360007',
 'KR7043370006',
 'KR7043610005',
 'KR7043910009',
 'KR7044060002',
 'KR7044340008',
 'KR7044480002',
 'KR7044490001',
 'KR7044780005',
 'KR7044960003',
 'KR7045060001',
 'KR7045100005',
 'KR7045340007',
 'KR7045390002',
 'KR7045520004',
 'KR7045660008',
 'KR7046070009',
 'KR7046110003',
 'KR7046120002',
 'KR7046140000',
 'KR7046210001',
 'KR7046310009',
 'KR7046390001',
 'KR7046440004',
 'KR7046890000',
 'KR7046940003',
 'KR7047080007',
 'KR7047310008',
 'KR7047770003',
 'KR7047820006',
 'KR7047920004',
 'KR7048260004',
 'KR7048410005',
 'KR7048430003',
 'KR7048470009',
 'KR7048530000',
 'KR7048550008',
 'KR7048770002',
 'KR7048830004',
 'KR7048870000',
 'KR7048910004',
 'KR7049070006',
 'KR7049080005',
 'KR7049180003',
 'KR7049430002',
 'KR7049470008',
 'KR7049480007',
 'KR7049520000',
 'KR7049630007',
 'KR7049950009',
 'KR7049960008',
 'KR7050110006',
 'KR7050120005',
 'KR7050760008',
 'KR7050860006',
 'KR7050890003',
 'KR7050960004',
 'KR7051160000',
 'KR7051360006',
 'KR7051370005',
 'KR7051490001',
 'KR7051500007',
 'KR7051780005',
 'KR7052020005',
 'KR7052220001',
 'KR7052260007',
 'KR7052290004',
 'KR7052300001',
 'KR7052330008',
 'KR7052400009',
 'KR7052420007',
 'KR7052600004',
 'KR7052670007',
 'KR7052710001',
 'KR7052770005',
 'KR7052790003',
 'KR7052900008',
 'KR7053030003',
 'KR7053050001',
 'KR7053060000',
 'KR7053110003',
 'KR7053160008',
 'KR7053260006',
 'KR7053270005',
 'KR7053280004',
 'KR7053290003',
 'KR7053300000',
 'KR7053350005',
 'KR7053450003',
 'KR7053590006',
 'KR7053610002',
 'KR7053700001',
 'KR7053800009',
 'KR7053950002',
 'KR7053980009',
 'KR7054040001',
 'KR7054050000',
 'KR7054090006',
 'KR7054180005',
 'KR7054210000',
 'KR7054220009',
 'KR7054340005',
 'KR7054410006',
 'KR7054450002',
 'KR7054540000',
 'KR7054620000',
 'KR7054630009',
 'KR7054670005',
 'KR7054780002',
 'KR7054920004',
 'KR7054940002',
 'KR7054950001',
 'KR7056080005',
 'KR7056090004',
 'KR7056190002',
 'KR7056360001',
 'KR7056700008',
 'KR7056730005',
 'KR7057030009',
 'KR7057500001',
 'KR7057540007',
 'KR7057680001',
 'KR7058110008',
 'KR7058220005',
 'KR7058420001',
 'KR7058450008',
 'KR7058470006',
 'KR7058530007',
 'KR7058610007',
 'KR7058630005',
 'KR7058820002',
 'KR7059090001',
 'KR7059100008',
 'KR7059120006',
 'KR7059210005',
 'KR7060150000',
 'KR7060230000',
 'KR7060240009',
 'KR7060250008',
 'KR7060260007',
 'KR7060280005',
 'KR7060300001',
 'KR7060310000',
 'KR7060370004',
 'KR7060480001',
 'KR7060540002',
 'KR7060560000',
 'KR7060570009',
 'KR7060590007',
 'KR7060720000',
 'KR7061040002',
 'KR7061250007',
 'KR7061970000',
 'KR7062860002',
 'KR7063080006',
 'KR7063170005',
 'KR7063440002',
 'KR7063570006',
 'KR7063760003',
 'KR7064090004',
 'KR7064240005',
 'KR7064260003',
 'KR7064480007',
 'KR7064520000',
 'KR7064550007',
 'KR7064760002',
 'KR7064800006',
 'KR7064820004',
 'KR7065060006',
 'KR7065130007',
 'KR7065160004',
 'KR7065170003',
 'KR7065350001',
 'KR7065420002',
 'KR7065440000',
 'KR7065450009',
 'KR7065500001',
 'KR7065510000',
 'KR7065560005',
 'KR7065570004',
 'KR7065620007',
 'KR7065650004',
 'KR7065660003',
 'KR7065680001',
 'KR7065710006',
 'KR7065940009',
 'KR7065950008',
 'KR7066110008',
 'KR7066130006',
 'KR7066310004',
 'KR7066410002',
 'KR7066590001',
 'KR7066620006',
 'KR7066670001',
 'KR7066700006',
 'KR7066790007',
 'KR7066900002',
 'KR7066910001',
 'KR7066970005',
 'KR7066980004',
 'KR7067000000',
 'KR7067080002',
 'KR7067160002',
 'KR7067170001',
 'KR7067280008',
 'KR7067290007',
 'KR7067310003',
 'KR7067390005',
 'KR7067630004',
 'KR7067730002',
 'KR7067900001',
 'KR7067990002',
 'KR7068240001',
 'KR7068270008',
 'KR7068330000',
 'KR7068760008',
 'KR7068790005',
 'KR7069080000',
 'KR7069110005',
 'KR7069330009',
 'KR7069510006',
 'KR7069540003',
 'KR7070590005',
 'KR7071200000',
 'KR7071280002',
 'KR7071460000',
 'KR7071670004',
 'KR7072020001',
 'KR7072470008',
 'KR7072950009',
 'KR7073070005',
 'KR7073110009',
 'KR7073190001',
 'KR7073490005',
 'KR7073560005',
 'KR7073570004',
 'KR7074430000',
 'KR7074600008',
 'KR7075130005',
 'KR7075970004',
 'KR7076080001',
 'KR7076610005',
 'KR7077360006',
 'KR7078070000',
 'KR7078130002',
 'KR7078140001',
 'KR7078150000',
 'KR7078160009',
 'KR7078340007',
 'KR7078350006',
 'KR7078590007',
 'KR7078600004',
 'KR7078650009',
 'KR7078860004',
 'KR7078890001',
 'KR7078940004',
 'KR7079170007',
 'KR7079370003',
 'KR7079650008',
 'KR7079810008',
 'KR7079940003',
 'KR7079950002',
 'KR7079970000',
 'KR7080000003',
 'KR7080010002',
 'KR7080160005',
 'KR7080220007',
 'KR7080420003',
 'KR7080470008',
 'KR7080530009',
 'KR7080580004',
 'KR7081580003',
 'KR7081970006',
 'KR7082210006',
 'KR7082270000',
 'KR7082660002',
 'KR7082800004',
 'KR7082850009',
 'KR7083310003',
 'KR7083450007',
 'KR7083470005',
 'KR7083500009',
 'KR7083550004',
 'KR7083640003',
 'KR7083650002',
 'KR7083660001',
 'KR7083790006',
 'KR7083930008',
 'KR7084110006',
 'KR7084180009',
 'KR7084370006',
 'KR7084650001',
 'KR7084730001',
 'KR7084990001',
 'KR7085370005',
 'KR7085660009',
 'KR7085670008',
 'KR7085810000',
 'KR7086040003',
 'KR7086060001',
 'KR7086390002',
 'KR7086450004',
 'KR7086520004',
 'KR7086900008',
 'KR7086960002',
 'KR7086980000',
 'KR7087010005',
 'KR7087260006',
 'KR7087600003',
 'KR7087730008',
 'KR7088130000',
 'KR7088290002',
 'KR7088390000',
 'KR7088800008',
 'KR7088910005',
 'KR7089010003',
 'KR7089030001',
 'KR7089140008',
 'KR7089150007',
 'KR7089230007',
 'KR7089530000',
 'KR7089600001',
 'KR7089850002',
 'KR7089980007',
 'KR7090150004',
 'KR7090360009',
 'KR7090410002',
 'KR7090460007',
 'KR7090470006',
 'KR7090710005',
 'KR7090730003',
 'KR7090850009',
 'KR7091120006',
 'KR7091340000',
 'KR7091580001',
 'KR7091590000',
 'KR7091700005',
 'KR7091970004',
 'KR7091990002',
 'KR7092040005',
 'KR7092070002',
 'KR7092130004',
 'KR7092300003',
 'KR7092600006',
 'KR7092730001',
 'KR7092870005',
 'KR7093190007',
 'KR7093380004',
 'KR7093520005',
 'KR7093640001',
 'KR7093920007',
 'KR7094170008',
 'KR7094190006',
 'KR7094360005',
 'KR7094480001',
 'KR7094820008',
 'KR7094840006',
 'KR7094850005',
 'KR7094940004',
 'KR7094970001',
 'KR7095190005',
 'KR7095270005',
 'KR7095300000',
 'KR7095340006',
 'KR7095500005',
 'KR7095610002',
 'KR7095660007',
 'KR7095700001',
 'KR7095910006',
 'KR7096040001',
 'KR7096240007',
 'KR7096350004',
 'KR7096530001',
 'KR7096630009',
 'KR7096640008',
 'KR7097520001',
 'KR7097780001',
 'KR7097870000',
 'KR7098120009',
 'KR7098460009',
 'KR7099190001',
 'KR7099220006',
 'KR7099320004',
 'KR7099410003',
 'KR7099440000',
 'KR7099830002',
 'KR7100030006',
 'KR7100120005',
 'KR7100130004',
 'KR7100660000',
 'KR7100700004',
 'KR7101000008',
 'KR7101170009',
 'KR7101330009',
 'KR7101390003',
 'KR7101490001',
 'KR7101670008',
 'KR7102120003',
 'KR7102710001',
 'KR7102940004',
 'KR7103230009',
 'KR7104040001',
 'KR7104200001',
 'KR7104480009',
 'KR7104830005',
 'KR7105550008',
 'KR7106080005',
 'KR7106520000',
 'KR7108230004',
 'KR7108320003',
 'KR7108380007',
 'KR7108790007',
 'KR7108860008',
 'KR7109610006',
 'KR7109740001',
 'KR7109960005',
 'KR7111820007',
 'KR7111870002',
 'KR7112040001',
 'KR7112240007',
 'KR7113810006',
 'KR7114120009',
 'KR7114190002',
 'KR7114570005',
 'KR7114630007',
 'KR7114810005',
 'KR7115160004',
 'KR7115180002',
 'KR7115440000',
 'KR7115450009',
 'KR7115500001',
 'KR7115530008',
 'KR7115610008',
 'KR7115960007',
 'KR7119500007',
 'KR7119610004',
 'KR7119850006',
 'KR7119860005',
 'KR7121440002',
 'KR7121600001',
 'KR7121800007',
 'KR7121850002',
 'KR7122350002',
 'KR7122450000',
 'KR7122640006',
 'KR7122800006',
 'KR7122870009',
 'KR7122990005',
 'KR7123100000',
 'KR7123330003',
 'KR7123410003',
 'KR7123420002',
 'KR7123570004',
 'KR7123840001',
 'KR7123860009',
 'KR7124500000',
 'KR7126600006',
 'KR7126640002',
 'KR7126700004',
 'KR7126870005',
 'KR7127160000',
 'KR7127710002',
 'KR7130500002',
 'KR7130580004',
 'KR7130740004',
 'KR7130960008',
 'KR7131030009',
 'KR7131090003',
 'KR7131180002',
 'KR7131220006',
 'KR7131370009',
 'KR7131390007',
 'KR7131400004',
 'KR7131760001',
 'KR7131970006',
 'KR7133750000',
 'KR7134060003',
 'KR7134580000',
 'KR7134780006',
 'KR7136480001',
 'KR7136510005',
 'KR7136540002',
 'KR7137400008',
 'KR7137940003',
 'KR7137950002',
 'KR7138070008',
 'KR7138080007',
 'KR7138360003',
 'KR7138690003',
 'KR7139050009',
 'KR7140070004',
 'KR7140410002',
 'KR7140520008',
 'KR7140860008',
 'KR7141000000',
 'KR7141020008',
 'KR7141070003',
 'KR7141080002',
 'KR7142210004',
 'KR7142280007',
 'KR7142760008',
 'KR7143240000',
 'KR7143540003',
 'KR7144510005',
 'KR7144960002',
 'KR7145020004',
 'KR7147760003',
 'KR7147830004',
 'KR7148250004',
 'KR7149940009',
 'KR7149950008',
 'KR7149980005',
 'KR7150840007',
 'KR7151860004',
 'KR7151910007',
 'KR7153490008',
 'KR7154040000',
 'KR7155650005',
 'KR7156100000',
 'KR7159580000',
 'KR7159910009',
 'KR7160550000',
 'KR7160600003',
 'KR7160980009',
 'KR7161570007',
 'KR7161580006',
 'KR7166090001',
 'KR7166480004',
 'KR7168330009',
 'KR7171120009',
 'KR7173940008',
 'KR7174880005',
 'KR7175140003',
 'KR7176440006',
 'KR7177350006',
 'KR7177830007',
 'KR7178320008',
 'KR7178780003',
 'KR7178920005',
 'KR7180400004',
 'KR7182360008',
 'KR7182400002',
 'KR7182690008',
 'KR7183300003',
 'KR7184230001',
 'KR7185490000',
 'KR7187220009',
 'KR7187270004',
 'KR7187420005',
 'KR7187790001',
 'KR7189300007',
 'KR7189690001',
 'KR7189860000',
 'KR7189980006',
 'KR7190510008',
 'KR7191410000',
 'KR7191420009',
 'KR7192080000',
 'KR7192250009',
 'KR7192390003',
 'KR7192410009',
 'KR7192440006',
 'KR7193250008',
 'KR7194480000',
 'KR7194510004',
 'KR7194610002',
 'KR7196170005',
 'KR7196300008',
 'KR7196450001',
 'KR7196490007',
 'KR7196700009',
 'KR7197210008',
 'KR7200130003',
 'KR7200230001',
 'KR7200470003',
 'KR7200670008',
 'KR7200710002',
 'KR7200780005',
 'KR7201490000',
 'KR7203450002',
 'KR7203650007',
 'KR7203690003',
 'KR7204840003',
 'KR7204990006',
 'KR7205100001',
 'KR7205500002',
 'KR7206400004',
 'KR7206560005',
 'KR7206640005',
 'KR7206650004',
 'KR7208140004',
 'KR7208370007',
 'KR7208710004',
 'KR7208860007',
 'KR7212560007',
 'KR7213090004',
 'KR7213420003',
 'KR7214180002',
 'KR7214270001',
 'KR7214370009',
 'KR7214430001',
 'KR7214450009',
 'KR7214870008',
 'KR7215000001',
 'KR7215100009',
 'KR7215360009',
 'KR7215600008',
 'KR7215790007',
 'KR7216050005',
 'KR7217190008',
 'KR7217270008',
 'KR7217480003',
 'KR7217620004',
 'KR7217730001',
 'KR7217820000',
 'KR7219130002',
 'KR7220100002',
 'KR7220180004',
 'KR7220260004',
 'KR7220630008',
 'KR7221610009',
 'KR7221840002',
 'KR7222040008',
 'KR7222110009',
 'KR7222420002',
 'KR7222800005',
 'KR7222980005',
 'KR7223310004',
 'KR7224060004',
 'KR7224110007',
 'KR7225190008',
 'KR7225530005',
 'KR7225570001',
 'KR7225650001',
 'KR7226350007',
 'KR7228340006',
 'KR7228850004',
 'KR7230360000',
 'KR7230980005',
 'KR7234920007',
 'KR7236200002',
 'KR7237690003',
 'KR7237750005',
 'KR7237880000',
 'KR7238090005',
 'KR7238120000',
 'KR7238490007',
 'KR7239610009',
 'KR7240810002',
 'KR7241520006',
 'KR7241710003',
 'KR7241790005',
 'KR7241820000',
 'KR7243070000',
 'KR7246690002',
 'KR7246720007',
 'KR7251370003',
 'KR7251630000',
 'KR7252500004',
 'KR7257730002',
 'KR7263770000',
 'KR7264450008',
 'KR7265520007',
 'KR7267980001',
 'KR7272290008',
 'KR8392070007']

In [41]:
Y

ISU_CD        ORD_DD    hourmin
KR7000250001  20170901  121         440.0
                        122         980.0
                        140        1010.0
                        141         160.0
                        142         370.0
                                    ...
KR8392070007  20170904  91          -14.0
                        113         -14.0
                        122         -15.0
                        132          44.0
                        133        1050.0
Name: ORD_QTY, Length: 85850, dtype: float64

In [42]:
len(X)

74024

In [43]:
len(Y)

85850

In [44]:

x=np.array(X[['시가','High','Low','매도총호가잔량','매수총호가잔량']])

y=np.array(Y)

In [45]:
len(X)

74024

In [46]:
len(y)

85850

In [47]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
# save to npy file
save('xdata.npy', x)
save('ydata.npy',y)

In [48]:
data_dir=path_dir+'/'+'ord201709'

file_list = os.listdir(data_dir)
print(file_list)
filecount=0
for filename in file_list:
    print(filename)
    if 'ksqord_2017090' not in filename:
        continue
    df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
    if 'SPOT' in filename:
        continue
        df1.columns = list(layout_1.iloc[0:len(df1.iloc[0])][0])
        print("Using 2013 data")
    elif 'ksqord_2017090' in filename:
        df1.columns= header_df
        df=df[1:]
        print("Using 2017 data")
    else:
        continue
#    df1=df1.set_index(['ORD_DD','ORD_ACPT_TM'])
    if(filecount==0):
        dftotISU=df1[df1['ISU_CD'].isin(ISU_CD_list)]
    else:
        dftotISU=pd.concat([dftotISU,df1[df1['ISU_CD'].isin(ISU_CD_list)],])
#         dfmost.join(df1[(df1['MBR_NO']==max_MBR_NO) & (df1['BRN_NO']==max_BRN_NO)],how='outer')
    filecount+=1

['ksqord_20170904.csv', 'ksqord_20170905.csv', 'ksqord_20170929.csv', 'ksqord_20170926.csv', 'ksqord_20170913.csv', 'ksqord_20170928.csv', 'ksqord_20170901.csv', 'ksqord_20170918.csv', 'ksqord_20170922.csv', 'ksqord_20170906.csv', 'ksqord_20170919.csv', 'ksqord_20170921.csv', 'ksqord_20170920.csv', 'ksqord_20170925.csv', 'ksqord_20170908.csv', 'ksqord_20170915.csv', 'ksqord_20170907.csv', 'ksqord_20170914.csv', 'ksqord_20170927.csv', 'ksqord_20170911.csv', 'ksqord_20170912.csv']
ksqord_20170904.csv
Using 2017 data
ksqord_20170905.csv
Using 2017 data
ksqord_20170929.csv
ksqord_20170926.csv
ksqord_20170913.csv
ksqord_20170928.csv
ksqord_20170901.csv
Using 2017 data
ksqord_20170918.csv
ksqord_20170922.csv
ksqord_20170906.csv
Using 2017 data
ksqord_20170919.csv
ksqord_20170921.csv
ksqord_20170920.csv
ksqord_20170925.csv
ksqord_20170908.csv
Using 2017 data
ksqord_20170915.csv
ksqord_20170907.csv
Using 2017 data
ksqord_20170914.csv
ksqord_20170927.csv
ksqord_20170911.csv
ksqord_20170912.csv

In [49]:
dftotISU['hourmin']=dftotISU['ORD_ACPT_TM']//1000000
dftotISU['시가']=(dftotISU['ASK_STEP1_BSTORD_PRC']+dftotISU['BID_STEP1_BSTORD_PRC'])/2
dftotISU['High']=(dftotISU['고가']-dftotISU['시가'])/dftotISU['시가']
dftotISU['Low']=(dftotISU['저가']-dftotISU['시가'])/dftotISU['시가']
dftotISU['count']=1


dftot=dftotISU.groupby(['ISU_CD','ORD_DD','hourmin']).sum()
#PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']=PdfAA['시가','High','Low','매도호가잔량','매수호가잔량']/PdfAA['count']
dftot['시가']=dftot['시가']/dftot['count']
dftot['High']=dftot['High']/dftot['count']
dftot['Low']=dftot['Low']/dftot['count']
dftot['매도총호가잔량']=dftot['매도총호가잔량']/dftot['count']
dftot['매수총호가잔량']=dftot['매수총호가잔량']/dftot['count']

dftot=dftot[['시가','High','Low','매도총호가잔량',
       '매수총호가잔량']]

In [50]:
X=dftot[['시가','High','Low','매도총호가잔량','매수총호가잔량']]
X=X.reset_index()
X=X[(X['ORD_DD']<20170908)&(X['hourmin']<153)&(X['hourmin']>86)]

In [51]:
X

,ISU_CD,ORD_DD,hourmin,시가,High,Low,매도총호가잔량,매수총호가잔량
8,KR7000250001,20170901,90,13182.990315,0.001026,-0.017589,50380.016949,46627.525424
9,KR7000250001,20170901,91,13257.142857,0.007007,-0.023165,64586.050420,53997.987395
10,KR7000250001,20170901,92,13487.103175,0.005698,-0.039765,81665.257143,64156.687302
11,KR7000250001,20170901,93,13444.871795,0.015270,-0.036795,117462.226107,67493.312354
12,KR7000250001,20170901,94,13526.666667,0.009118,-0.042631,127686.404167,74264.875000
...,...,...,...,...,...,...,...,...
320120,KR8392070007,20170907,144,5885.172414,0.029709,-0.005974,61946.827586,25573.724138
320121,KR8392070007,20170907,145,5894.722222,0.028041,-0.007584,63079.888889,25556.000000
320122,KR8392070007,20170907,150,5871.190476,0.032160,-0.003608,63610.000000,24622.190476
320123,KR8392070007,20170907,151,5876.666667,0.031198,-0.004536,62983.125000,23223.166667
320124,KR8392070007,20170907,152,5864.000000,0.033425,-0.002387,63651.400000,22003.520000

In [52]:
ISU_CD_list2= (X.groupby(['ISU_CD']).count()['hourmin'] == 195)

In [53]:
ISU_CD_list2=X.groupby(['ISU_CD']).count().index[(X.groupby(['ISU_CD']).count()['hourmin'] == 195)]

In [54]:
X=X[X['ISU_CD'].isin(ISU_CD_list2)]

In [55]:
X=X.set_index(['ISU_CD','ORD_DD','hourmin'])

In [56]:
Y=Y.reset_index()

In [57]:
Y=Y[Y['ISU_CD'].isin(ISU_CD_list2)]

In [58]:
Y=Y.set_index(['ISU_CD','ORD_DD','hourmin'])

In [59]:
Y

                               ORD_QTY
ISU_CD       ORD_DD   hourmin
KR7000250001 20170901 121        440.0
                      122        980.0
                      140       1010.0
                      141        160.0
                      142        370.0
...                                ...
KR8392070007 20170904 91         -14.0
                      113        -14.0
                      122        -15.0
                      132         44.0
                      133       1050.0

[81282 rows x 1 columns]

In [60]:
X['ORD_QTY']=Y

In [61]:
Data=X
# save numpy array as npy file
from numpy import asarray
from numpy import save
# save to npy file
save('Data.npy', Data)

In [62]:
from torch.utils.data import DataLoader, random_split

lobdata=LOBDataset(x,y)


dataset_train, dataset_test = random_split(lobdata, (180, 15))

NameError: name 'LOBDataset' is not defined


lobdataloader = DataLoader(lobdata)
for data in dataloader_train:
    print(data[0])

In [ ]:
dataloader_train = DataLoader(dataset_train,
                              batch_size=BATCH_SIZE,
                              shuffle=True,
                              num_workers=NUM_WORKERS,
                              pin_memory=False
                             )
dataloader_test = DataLoader(dataset_test,
                             batch_size=BATCH_SIZE,
                             shuffle=False,
                             num_workers=NUM_WORKERS
                            )

In [ ]:
len(dataloader_train)

In [ ]:
import json
from typing import Optional

import numpy as np
from torch.utils.data import Dataset
import torch


class LOBDataset(Dataset):
    """Torch dataset for Oze datachallenge.

    Load dataset from a single npz file.

    Attributes
    ----------
    labels: :py:class:`dict`
        Ordered labels list for R, Z and X.

    Parameters
    ---------
    dataset_path:
        Path to the dataset inputs as npz.
    labels_path:
        Path to the labels, divided in R, Z and X, in json format.
        Default is "labels.json".
    normalize:
        Data normalization method, one of ``'mean'``, ``'max'`` or ``None``.
        Default is ``'max'``.
    """

    def __init__(self,
                 X: np.array,Y: np.array,
                 **kwargs):
        """Load dataset from npz."""
        super().__init__(**kwargs)

        self._x=torch.Tensor(X)
        self._y=torch.Tensor(Y)



    def _load_npz(self, dataset_path, labels_path):
        # Load dataset as csv
        dataset = np.load(dataset_path)

        # Load labels, can be found through csv or challenge description
        with open(labels_path, "r") as stream_json:
            self.labels = json.load(stream_json)

        R = dataset['R'].astype(np.float32)
        X = dataset['X'].astype(np.float32)
        Z = dataset['Z'].astype(np.float32)

        m = Z.shape[0]  # Number of training example
        K = Z.shape[1]  # Time serie length

        R = np.tile(R[:, np.newaxis, :], (1, K, 1))

        # Store R, Z and X as x and y
        #self._x = np.concatenate([Z, R], axis=-1)
        self._x = Z
        self._y = X

        # Normalize
        if self._normalize == "mean":
            mean = np.mean(self._x, axis=(0, 1))
            std = np.std(self._x, axis=(0, 1))
            self._x = (self._x - mean) / (std + np.finfo(float).eps)

            self._mean = np.mean(self._y, axis=(0, 1))
            self._std = np.std(self._y, axis=(0, 1))
            self._y = (self._y - self._mean) / (self._std + np.finfo(float).eps)
        elif self._normalize == "max":
            M = np.max(self._x, axis=(0, 1))
            m = np.min(self._x, axis=(0, 1))
            self._x = (self._x - m) / (M - m + np.finfo(float).eps)

            self._M = np.max(self._y, axis=(0, 1))
            self._m = np.min(self._y, axis=(0, 1))
            self._y = (self._y - self._m) / (self._M - self._m + np.finfo(float).eps)
        elif self._normalize is None:
            pass
        else:
            raise(
                NameError(f'Normalize method "{self._normalize}" not understood.'))

        # Convert to float32
        self._x = torch.Tensor(self._x)
        self._y = torch.Tensor(self._y)

    def rescale(self,
                y: np.ndarray,
                idx_label: int) -> torch.Tensor:
        """Rescale output from initial normalization.

        Arguments
        ---------
        y:
            Array to resize, of shape (K,).
        idx_label:
            Index of the output label.
        """
        if self._normalize == "max":
            return y * (self._M[idx_label] - self._m[idx_label] + np.finfo(float).eps) + self._m[idx_label]
        elif self._normalize == "mean":
            return y * (self._std[idx_label] + np.finfo(float).eps) + self._mean[idx_label]
        else:
            raise(
                NameError(f'Normalize method "{self._normalize}" not understood.'))

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        return (self._x[idx], self._y[idx])

    def __len__(self):
        return self._x.shape[0]

In [ ]:
len(LOBDataset)

In [ ]:
A[]/A['count']