In [1]:
### 필요 라이브러리
import os
import pandas as pd
import numpy as np
import datetime as dt
import math
import warnings
import pickle
warnings.filterwarnings(action='ignore')

### 데이터 보여지는 개수 설정
pd.set_option('display.max_columns', 40)
pd.set_option('display.max_rows', 300)

In [2]:
### 폴더에 존재하는 파일 리스트, 굳이 실행하지 않아도 됨
# path_dir = 'C:/Users/HONGJEONGUI/Desktop/RA/Data/DataOR'
path_dir = '/Data/Data'
 
file_list = os.listdir(path_dir)
print(file_list)

['PT구분코드(전체조회기간).xlsx', 'stktrd_20150102.csv', 'ord201709', 'stkord_20150102.csv.gz', 'ORD_19990104.csv', 'layout_3.csv', '시장정보 데이터 확인 및 요청_레이아웃.xlsx', 'layout_2.csv', '유가 체결장 2단계 샘플.csv', 'layout_1.csv', 'SPOT_TRD_20130102.csv', 'ord', '유가 호가장 2단계 샘플.csv', '코스닥 체결장 2단계 샘플.csv', 'TRD_19990104.csv', '코스닥 호가장 2단계 샘플.csv', 'ksqtrd_20150102.csv']

In [3]:
### 유재인 교수님께서 공유해주신 레이블, 코드 설명 엑셀파일(xlsx)을 (시트가 3개) 각 시트별로 csv로 저장.
### 1번째 위치는 엑셀파일위치, 2,3번째는 코드 저장 위치
def get_raw_column():
    sheets = 3
    for i in range(1,sheets+1):
        df = pd.read_excel(path_dir+"/시장정보 데이터 확인 및 요청_레이아웃.xlsx", sheet_name=(i-1))
        df.to_csv((path_dir+"/layout_{}.csv").format(i), encoding = "cp949", sep=',', header = False, index = False)
        globals()['layout_{}'.format(i)] = pd.read_csv((path_dir+"/layout_{}.csv").format(i), header = None, encoding="cp949")
    return list(layout_1[:][0])

### 유재인 교수님께서 공유해주신 레이블, 코드 설명 엑셀파일(xlsx)을 (시트가 3개) 각 시트별로 csv로 저장.
### 1번째 위치는 엑셀파일위치, 2,3번째는 코드 저장 위치

    sheets = 3
    for i in range(1,sheets+1):
        df = pd.read_excel(path_dir+"/시장정보 데이터 확인 및 요청_레이아웃.xlsx", sheet_name=(i-1))
        df.to_csv((path_dir+"/layout_{}.csv").format(i), encoding = "cp949", sep=',', header = False, index = False)
        globals()['layout_{}'.format(i)] = pd.read_csv((path_dir+"/layout_{}.csv").format(i), header = None, encoding="cp949")

In [4]:
df = pd.read_csv(path_dir+"/코스닥 호가장 2단계 샘플.csv",encoding='cp949')

In [5]:
header_df=['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD', '호가장처리가격',
       'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD', 'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC',
       'ASK_STEP1_BSTORD_RQTY', 'ASK_STEP2_BSTORD_PRC','ASK_STEP2_BSTORD_RQTY','ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY','ASK_STEP4_BSTORD_PRC', 'ASK_STEP4_BSTORD_RQTY','ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY',
       'BID_STEP1_BSTORD_PRC', 'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC', 'BID_STEP2_BSTORD_RQTY',
       'BID_STEP3_BSTORD_PRC', 'BID_STEP3_BSTORD_RQTY','BID_STEP4_BSTORD_PRC', 'BID_STEP4_BSTORD_RQTY',
       'BID_STEP5_BSTORD_PRC', 'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD', 'FORNINVST_TP_CD',
       'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량', '매도총호가잔량', '매수총호가잔량',
       '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금', 'AGG_TM', '시가', '고가', '저가',
       'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드', 'MKTSTAT_TP_CD', '매도10단계호가합계잔량',
       '매수10단계호가합계잔량', 'PT_TP_CD']
header = header_df

 
df.columns=header_df
df=df[1:]
df.head()

,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,ORD_COND_CD,INVST_TP_CD,ASK_STEP1_BSTORD_PRC,ASK_STEP1_BSTORD_RQTY,ASK_STEP2_BSTORD_PRC,ASK_STEP2_BSTORD_RQTY,ASK_STEP3_BSTORD_PRC,ASK_STEP3_BSTORD_RQTY,ASK_STEP4_BSTORD_PRC,ASK_STEP4_BSTORD_RQTY,ASK_STEP5_BSTORD_PRC,...,회원사주문시각,예상체결가격,예상체결수량,매도총호가잔량,매수총호가잔량,호가체결접수순서번호,직전체결가격,누적체결수량,누적거래대금,AGG_TM,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD
1,KR7009620006,20171030,23650,1,0,19550,2,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125949640,0,0,21901,29871,34709,19550,0,0,0,15350,19850,14400,0,2,0,40,4465,4210,0
2,KR7009620006,20171030,23651,1,0,19500,1,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125949734,0,0,21901,29871,34710,19550,77,1505350,125949735,15350,19850,14400,0,2,0,40,4465,4210,0
3,KR7009620006,20171030,23652,1,0,19550,1,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125950114,0,0,21901,29794,34712,19550,5,97750,125950115,15350,19850,14400,0,2,0,40,4465,4133,0
4,KR7009620006,20171030,23653,1,0,19250,2,1,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125950375,0,0,21901,29919,34714,19550,130,2502500,130058726,15350,19850,14400,0,2,0,40,4465,4258,0
5,KR7009620006,20171030,23654,1,0,19600,2,2,2,0,8000,19650,5,19700,582,19750,385,19800,609,19850,...,125950687,0,0,21901,29919,34715,19550,0,0,0,15350,19850,14400,23599,2,0,40,4465,3432,0

data_dir=path_dir+'/'+'ord'

UUID_count={}
file_list = os.listdir(data_dir)
print(file_list)
columnlist=['MBR_NO','BRN_NO']
filecount=0
for filename in file_list:
    print(filename)
    df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
    if 'SPOT' in filename:
        df1.columns = list(layout_1.iloc[0:len(df1.iloc[0])][0])
        print("Using 2013 data")
    else:
        continue
    if(filecount==0):
        countdf=df1.groupby(columnlist).size()
    else:
        countdf=countdf.add(df1.groupby(columnlist).size())
    filecount+=1
    break

list(layout_1.iloc[0:len(df1.iloc[0])][0])

In [6]:
raw_column=get_raw_column()

In [7]:
def get_datacount(data_dir,columnlist):
    file_list = os.listdir(data_dir)
    filecount=0
    for filename in file_list:
        print(filename)
        df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
        df1.columns= header_df
        if(filecount==0):
            countdf=df1.groupby(columnlist).size()
        else:
            countdf=countdf.add(df1.groupby(columnlist).size())
        filecount+=1
        break
    return countdf

In [8]:
data_dir=path_dir+'/'+'ord201709'

countdf=get_datacount(data_dir,['MBR_NO','BRN_NO'])
countdf2=get_datacount(data_dir,['ISU_CD'])

max_MBR_NO,max_BRN_NO=countdf.idxmax()
ISU_CD=countdf2.idxmax()

print(max_MBR_NO,max_BRN_NO,ISU_CD)
#36 1 KR7068270008

ISU_CD='KR7068270008'

In [9]:
MBR_NO,BRN_NO=36,1

위에서 구한 종목과 기관 데이터 가지고 오기

In [10]:
def get_selectdata(data_dir,columnlist,valuelist,file_list=None,sel_columns=None):
    if(file_list is None):
        file_list = os.listdir(data_dir)
    print(file_list)
    filecount=0
    for filename in file_list:
#         if 'ksqord_2017090' not in filename:
#             continue
        print(filename)
        df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
        df1.columns= header_df
#         dfbool=None
        dfbool=df1['ISU_CD'].str.contains('KR')
        for i in range(len(columnlist)):
#             if i==0:
#                 dfbool=(df1[columnlist[i]]==valuelist[i])
#             else :
            dfbool= dfbool & (df1[columnlist[i]]==valuelist[i])
        if(sel_columns is not None):
            if(filecount==0):
                df=df1[dfbool][sel_columns]####기관의 거래에 대한 모든 데이터
            else:
                df=pd.concat([df,df1[dfbool][sel_columns],])
        else:
            if(filecount==0):
                df=df1[dfbool]####기관의 거래에 대한 모든 데이터
            else:
                df=pd.concat([df,df1[dfbool],])
        filecount+=1
    df.sort_values(by=['ORD_DD','ISU_CD','ORD_ACPT_TM'])
    return df

In [11]:
file_list=['ksqord_20170904.csv',
 'ksqord_20170905.csv',
 'ksqord_20170901.csv',
 'ksqord_20170906.csv',
 'ksqord_20170908.csv',
 'ksqord_20170907.csv']
# file_list=[ 'ksqord_20170901.csv']

In [12]:
columns=['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD',
       '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC', 'ASK_STEP1_BSTORD_RQTY',
       'ASK_STEP2_BSTORD_PRC', 'ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_PRC',
       'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY', 'BID_STEP1_BSTORD_PRC',
       'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC',
       'BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_PRC',
       'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_PRC',
       'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_PRC',
       'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD',
       'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금',
       'AGG_TM', '시가', '고가', '저가', 'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드',
       'MKTSTAT_TP_CD', '매도10단계호가합계잔량', '매수10단계호가합계잔량', 'PT_TP_CD', 'hourmin']
columns=['호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 
         'ORD_QTY', 'ORD_PRC', '매도총호가잔량',
       '매수총호가잔량', '직전체결가격', '누적체결수량', '누적거래대금', '시가', '고가', '저가',
        'hourmin']
columns= [ '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
        'CNTR_CD', 'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '직전체결가격', '누적체결수량', '누적거래대금',
         '시가', '고가', '저가',  'MKTSTAT_TP_CD', 'hourmin']
columns= [ '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_QTY', 'ORD_PRC',
       '매도총호가잔량', '매수총호가잔량', '직전체결가격', 
         '시가', '고가', '저가',  'MKTSTAT_TP_CD', 'hourmin']

columns=['ISU_CD','ORD_DD','ASKBID_TP_CD', 'MODCANCL_TP_CD',  'ASK_STEP1_BSTORD_PRC','BID_STEP1_BSTORD_PRC','ORD_ACPT_TM',
         'ORD_QTY', 'ORD_PRC', '매도총호가잔량',
       '매수총호가잔량',  '시가', '고가', '저가','hms']#for simple data

columns=['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD',
       '호가장처리가격', 'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD',
       'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC', 'ASK_STEP1_BSTORD_RQTY',
       'ASK_STEP2_BSTORD_PRC', 'ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_PRC',
       'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY', 'BID_STEP1_BSTORD_PRC',
       'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC',
       'BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_PRC',
       'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_PRC',
       'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_PRC',
       'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD',
       'FORNINVST_TP_CD', 'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량',
       '매도총호가잔량', '매수총호가잔량', '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금',
       'AGG_TM', '시가', '고가', '저가', 'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드',
       'MKTSTAT_TP_CD', '매도10단계호가합계잔량', '매수10단계호가합계잔량', 'PT_TP_CD', 'hourmin']

In [13]:
sel_columns=['ISU_CD','ORD_DD','ASKBID_TP_CD', 'MODCANCL_TP_CD',  'ASK_STEP1_BSTORD_PRC','BID_STEP1_BSTORD_PRC','ORD_ACPT_TM',
         'ORD_QTY', 'ORD_PRC', '매도총호가잔량',
       '매수총호가잔량',  '시가', '고가', '저가']
sel_columns=['ISU_CD','ORD_DD','ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ASK_STEP1_BSTORD_PRC', 'ASK_STEP1_BSTORD_RQTY',
       'ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_RQTY', 
       'ASK_STEP4_BSTORD_RQTY', 
       'ASK_STEP5_BSTORD_RQTY', 'BID_STEP1_BSTORD_PRC',
       'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_RQTY', 
       'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_RQTY', 
       'BID_STEP5_BSTORD_RQTY','ORD_ACPT_TM',
         'ORD_QTY', 'ORD_PRC', '매도총호가잔량',
       '매수총호가잔량',  '시가', '고가', '저가']

In [14]:
# Pdf=get_selectdata(data_dir,['MBR_NO','BRN_NO'],[MBR_NO,BRN_NO],file_list=file_list,sel_columns=sel_columns)
Pdf=get_selectdata(data_dir,['MBR_NO','BRN_NO'],[MBR_NO,BRN_NO],sel_columns=sel_columns)

['ksqord_20170904.csv', 'ksqord_20170905.csv', 'ksqord_20170929.csv', 'ksqord_20170926.csv', 'ksqord_20170913.csv', 'ksqord_20170928.csv', 'ksqord_20170901.csv', 'ksqord_20170918.csv', 'ksqord_20170922.csv', 'ksqord_20170906.csv', 'ksqord_20170919.csv', 'ksqord_20170921.csv', 'ksqord_20170920.csv', 'ksqord_20170925.csv', 'ksqord_20170908.csv', 'ksqord_20170915.csv', 'ksqord_20170907.csv', 'ksqord_20170914.csv', 'ksqord_20170927.csv', 'ksqord_20170911.csv', 'ksqord_20170912.csv']
ksqord_20170904.csv
ksqord_20170905.csv
ksqord_20170929.csv
ksqord_20170926.csv
ksqord_20170913.csv
ksqord_20170928.csv
ksqord_20170901.csv
ksqord_20170918.csv
ksqord_20170922.csv
ksqord_20170906.csv
ksqord_20170919.csv
ksqord_20170921.csv
ksqord_20170920.csv
ksqord_20170925.csv
ksqord_20170908.csv
ksqord_20170915.csv
ksqord_20170907.csv
ksqord_20170914.csv
ksqord_20170927.csv
ksqord_20170911.csv
ksqord_20170912.csv

#모은 데이터를 활용해서 전처리 과정

In [15]:
Pdf['hms']=Pdf['ORD_ACPT_TM']//1000
Pdf['hms']=Pdf['ORD_ACPT_TM']//1000000

Pdf=Pdf[(Pdf['ORD_DD']<20170908)&(Pdf['hms']<153)&(Pdf['hms']>86)]
Pdf=Pdf[Pdf['시가']!=0]

In [16]:
def get_hlcol(Pdf):
    Pdf['현재가']=(Pdf['ASK_STEP1_BSTORD_PRC']+Pdf['BID_STEP1_BSTORD_PRC'])/2
    Pdf['High']=(Pdf['고가']-Pdf['시가'])/Pdf['시가']
    Pdf['Low']=(Pdf['저가']-Pdf['시가'])/Pdf['시가']
    Pdf['현재가']=(Pdf['현재가']-Pdf['시가'])/Pdf['시가']
    return Pdf

In [17]:
def get_hmsPdf(Pdf,columnlist,outcolumnlist):
    Pdf['count']=1
    Pdf=Pdf.groupby(['ISU_CD','ORD_DD','hms']).sum()
    for col in columnlist:
        Pdf[col]=Pdf[col]/Pdf['count']
    Pdf=Pdf[outcolumnlist]
    return Pdf

In [18]:
Pdf=Pdf[Pdf['ORD_PRC']!=0]
Pdf=Pdf[Pdf['MODCANCL_TP_CD']==1]
Pdf=get_hlcol(Pdf)
Pdf['ORD_NET']=Pdf['ORD_PRC']*Pdf['ORD_QTY']

In [19]:
PdfA=Pdf[Pdf['ASKBID_TP_CD']==1]
PdfB=Pdf[Pdf['ASKBID_TP_CD']==2]

In [20]:
#hmscollist=['시가','현재가','High','Low','매도총호가잔량','매수총호가잔량']
#outhmscollist=['시가','현재가','High','Low','매도총호가잔량','매수총호가잔량','ORD_NET','ORD_QTY']
hmscollist=['시가','현재가','High','Low','매도총호가잔량','매수총호가잔량',
            'ASK_STEP1_BSTORD_RQTY','ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_RQTY',
            'BID_STEP1_BSTORD_RQTY','BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_RQTY']
outhmscollist=['시가','현재가','High','Low','매도총호가잔량','매수총호가잔량','ORD_NET','ORD_QTY',
               'ASK_STEP1_BSTORD_RQTY','ASK_STEP2_BSTORD_RQTY', 'ASK_STEP3_BSTORD_RQTY', 'ASK_STEP4_BSTORD_RQTY', 'ASK_STEP5_BSTORD_RQTY',
               'BID_STEP1_BSTORD_RQTY','BID_STEP2_BSTORD_RQTY', 'BID_STEP3_BSTORD_RQTY', 'BID_STEP4_BSTORD_RQTY', 'BID_STEP5_BSTORD_RQTY']

In [21]:
PdfAA=get_hmsPdf(PdfA,hmscollist,outhmscollist)
PdfBB=get_hmsPdf(PdfB,hmscollist,outhmscollist)

In [22]:
ISU_CD_list=(Pdf.groupby(['ISU_CD']).count().reset_index())['ISU_CD'].to_list()

In [23]:
with open("test"+str(MBR_NO)+".txt", "wb") as fp:   #Pickling
      pickle.dump(ISU_CD_list, fp)

In [24]:
len(ISU_CD_list)

929

In [30]:
def get_ISUdata(data_dir,ISUlist,file_list=None,sel_columns=None):
    if(file_list is None):
        file_list = os.listdir(data_dir)
    print(file_list)
    filecount=0
    for filename in file_list:
        print(filename)
        df1 = pd.read_csv(data_dir+'/'+filename, sep=',', header=None, encoding="cp949")
        df1.columns= header_df
        dfbool=df1['ISU_CD'].str.contains('KR')
        dfbool = dfbool &  df1['ISU_CD'].isin(ISUlist)
        dfbool = dfbool & (df1['ORD_DD']<20170908)
        dfbool = dfbool & (df1['ORD_ACPT_TM']<153*1000000)
        dfbool = dfbool & (df1['ORD_ACPT_TM']>86*1000000)
        if(sel_columns is not None):
            if(filecount==0):
                df=df1[dfbool][sel_columns]####기관의 거래에 대한 모든 데이터
            else:
                df=pd.concat([df,df1[dfbool][sel_columns],])
        else:
            if(filecount==0):
                df=df1[dfbool]####기관의 거래에 대한 모든 데이터
            else:
                df=pd.concat([df,df1[dfbool],])
        filecount+=1
    df.sort_values(by=['ORD_DD','ISU_CD','ORD_ACPT_TM'])
    return df

In [47]:
# X=get_ISUdata(data_dir,ISU_CD_list,file_list=file_list,sel_columns=sel_columns)
X=get_ISUdata(data_dir,ISU_CD_list,sel_columns=sel_columns)

['ksqord_20170904.csv', 'ksqord_20170905.csv', 'ksqord_20170929.csv', 'ksqord_20170926.csv', 'ksqord_20170913.csv', 'ksqord_20170928.csv', 'ksqord_20170901.csv', 'ksqord_20170918.csv', 'ksqord_20170922.csv', 'ksqord_20170906.csv', 'ksqord_20170919.csv', 'ksqord_20170921.csv', 'ksqord_20170920.csv', 'ksqord_20170925.csv', 'ksqord_20170908.csv', 'ksqord_20170915.csv', 'ksqord_20170907.csv', 'ksqord_20170914.csv', 'ksqord_20170927.csv', 'ksqord_20170911.csv', 'ksqord_20170912.csv']
ksqord_20170904.csv
ksqord_20170905.csv
ksqord_20170929.csv
ksqord_20170926.csv
ksqord_20170913.csv
ksqord_20170928.csv
ksqord_20170901.csv
ksqord_20170918.csv
ksqord_20170922.csv
ksqord_20170906.csv
ksqord_20170919.csv
ksqord_20170921.csv
ksqord_20170920.csv
ksqord_20170925.csv
ksqord_20170908.csv
ksqord_20170915.csv
ksqord_20170907.csv
ksqord_20170914.csv
ksqord_20170927.csv
ksqord_20170911.csv
ksqord_20170912.csv

In [48]:
X['hms']=X['ORD_ACPT_TM']//1000000
#X=X[(X['ORD_DD']<20170908)&(X['hms']<153)&(X['hms']>86)]
X=X[X['시가']!=0]

In [49]:

X=get_hlcol(X)

In [69]:
X=get_hmsPdf(X,hmscollist,hmscollist)

In [70]:
X

                                시가       현재가      High    Low        매도총호가잔량  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90   12950.0  0.017992  0.019043  0.000   50380.016949
                      91   12950.0  0.023718  0.030888  0.000   64586.050420
                      92   12950.0  0.041475  0.047411  0.000   81665.257143
                      93   12950.0  0.038214  0.054054  0.000  117462.226107
                      94   12950.0  0.044530  0.054054  0.000  127686.404167
...                            ...       ...       ...    ...            ...
KR8392070007 20170907 144   6000.0 -0.019138  0.010000 -0.025   61946.827586
                      145   6000.0 -0.017546  0.010000 -0.025   63079.888889
                      150   6000.0 -0.021468  0.010000 -0.025   63610.000000
                      151   6000.0 -0.020556  0.010000 -0.025   62983.125000
                      152   6000.0 -0.022667  0.010000 -0.025   63651.400000

                                매수총호가잔량  ASK_STEP1_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90   46627.525424            1701.859564
                      91   53997.987395             949.672269
                      92   64156.687302            1567.811111
                      93   67493.312354             921.853147
                      94   74264.875000            2543.633333
...                                 ...                    ...
KR8392070007 20170907 144  25573.724138             526.068966
                      145  25556.000000             706.444444
                      150  24622.190476             394.619048
                      151  23223.166667             374.208333
                      152  22003.520000             859.560000

                           ASK_STEP2_BSTORD_RQTY  ASK_STEP3_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1936.694915            1553.389831
                      91             1262.609244            1589.857143
                      92             2127.057143            2754.607937
                      93             1886.431235            2860.261072
                      94             4339.054167            4927.541667
...                                          ...                    ...
KR8392070007 20170907 144            1129.103448            1274.689655
                      145            1305.722222            1371.666667
                      150             292.095238             944.952381
                      151             474.125000             998.541667
                      152             433.000000            1037.440000

                           ASK_STEP4_BSTORD_RQTY  ASK_STEP5_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1302.907990             966.075061
                      91             1464.331933            2529.155462
                      92             3217.973016            3261.119048
                      93             3708.081585            5036.403263
                      94             7944.412500            6293.783333
...                                          ...                    ...
KR8392070007 20170907 144             240.517241            1058.620690
                      145             437.777778            1182.833333
                      150            1378.714286            1007.190476
                      151            1128.041667             314.500000
                      152               0.000000               0.000000

                           BID_STEP1_BSTORD_RQTY  BID_STEP2_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90              979.355932             894.634383
                      91             1243.915966            1923.315126
                      92             1487.750794            1904.317460
                      93             1409.517483            2214.512821
                      94             2390.666667            3029.050000
...                                          ...                    ...
KR8392070007 20170907 144             459.172414            1228.896552
                      145              30.833333             277.388889
                      150             223.904762            1405.000000
                      151             351.583333             704.083333
                      152             470.920000             951.200000

                           BID_STEP3_BSTORD_RQTY  BID_STEP4_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1425.489104            2691.418886
                      91             2680.928571            2836.088235
                      92             2119.439683            1964.261905
                      93             2898.333333            3851.666667
                      94             2454.670833            2250.645833
...                                          ...                    ...
KR8392070007 20170907 144            1646.793103            1522.137931
                      145             722.388889            1099.055556
                      150            1865.666667            1014.047619
                      151             798.291667            1052.083333
                      152            1819.480000               0.000000

                           BID_STEP5_BSTORD_RQTY
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             2842.012107
                      91             2823.722689
                      92             2221.347619
                      93             3860.524476
                      94             4027.200000
...                                          ...
KR8392070007 20170907 144             975.275862
                      145            1370.888889
                      150            1205.619048
                      151            1009.625000
                      152               0.000000

[180906 rows x 16 columns]

In [71]:
#X=X[['시가','현재가','High','Low','매도총호가잔량','매수총호가잔량']]#
X=X.reset_index()
Y=PdfAA.add(-1*PdfBB,fill_value=0)['ORD_QTY']

In [72]:
X=X.set_index(['ISU_CD','ORD_DD','hms'])

In [73]:
Y=Y.reset_index()

In [74]:
Y=Y.set_index(['ISU_CD','ORD_DD','hms'])

In [75]:
X['ORD_QTY']=Y

In [76]:
X['ORD_QTY']=X['ORD_QTY'].fillna(0)

In [77]:
X

                                시가       현재가      High    Low        매도총호가잔량  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90   12950.0  0.017992  0.019043  0.000   50380.016949
                      91   12950.0  0.023718  0.030888  0.000   64586.050420
                      92   12950.0  0.041475  0.047411  0.000   81665.257143
                      93   12950.0  0.038214  0.054054  0.000  117462.226107
                      94   12950.0  0.044530  0.054054  0.000  127686.404167
...                            ...       ...       ...    ...            ...
KR8392070007 20170907 144   6000.0 -0.019138  0.010000 -0.025   61946.827586
                      145   6000.0 -0.017546  0.010000 -0.025   63079.888889
                      150   6000.0 -0.021468  0.010000 -0.025   63610.000000
                      151   6000.0 -0.020556  0.010000 -0.025   62983.125000
                      152   6000.0 -0.022667  0.010000 -0.025   63651.400000

                                매수총호가잔량  ASK_STEP1_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90   46627.525424            1701.859564
                      91   53997.987395             949.672269
                      92   64156.687302            1567.811111
                      93   67493.312354             921.853147
                      94   74264.875000            2543.633333
...                                 ...                    ...
KR8392070007 20170907 144  25573.724138             526.068966
                      145  25556.000000             706.444444
                      150  24622.190476             394.619048
                      151  23223.166667             374.208333
                      152  22003.520000             859.560000

                           ASK_STEP2_BSTORD_RQTY  ASK_STEP3_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1936.694915            1553.389831
                      91             1262.609244            1589.857143
                      92             2127.057143            2754.607937
                      93             1886.431235            2860.261072
                      94             4339.054167            4927.541667
...                                          ...                    ...
KR8392070007 20170907 144            1129.103448            1274.689655
                      145            1305.722222            1371.666667
                      150             292.095238             944.952381
                      151             474.125000             998.541667
                      152             433.000000            1037.440000

                           ASK_STEP4_BSTORD_RQTY  ASK_STEP5_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1302.907990             966.075061
                      91             1464.331933            2529.155462
                      92             3217.973016            3261.119048
                      93             3708.081585            5036.403263
                      94             7944.412500            6293.783333
...                                          ...                    ...
KR8392070007 20170907 144             240.517241            1058.620690
                      145             437.777778            1182.833333
                      150            1378.714286            1007.190476
                      151            1128.041667             314.500000
                      152               0.000000               0.000000

                           BID_STEP1_BSTORD_RQTY  BID_STEP2_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90              979.355932             894.634383
                      91             1243.915966            1923.315126
                      92             1487.750794            1904.317460
                      93             1409.517483            2214.512821
                      94             2390.666667            3029.050000
...                                          ...                    ...
KR8392070007 20170907 144             459.172414            1228.896552
                      145              30.833333             277.388889
                      150             223.904762            1405.000000
                      151             351.583333             704.083333
                      152             470.920000             951.200000

                           BID_STEP3_BSTORD_RQTY  BID_STEP4_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1425.489104            2691.418886
                      91             2680.928571            2836.088235
                      92             2119.439683            1964.261905
                      93             2898.333333            3851.666667
                      94             2454.670833            2250.645833
...                                          ...                    ...
KR8392070007 20170907 144            1646.793103            1522.137931
                      145             722.388889            1099.055556
                      150            1865.666667            1014.047619
                      151             798.291667            1052.083333
                      152            1819.480000               0.000000

                           BID_STEP5_BSTORD_RQTY  ORD_QTY
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             2842.012107      0.0
                      91             2823.722689      0.0
                      92             2221.347619      0.0
                      93             3860.524476      0.0
                      94             4027.200000      0.0
...                                          ...      ...
KR8392070007 20170907 144             975.275862      0.0
                      145            1370.888889      0.0
                      150            1205.619048      0.0
                      151            1009.625000      0.0
                      152               0.000000      0.0

[180906 rows x 17 columns]

In [78]:
Data=X

In [79]:
Data=Data[Data.groupby(['ISU_CD','ORD_DD']).size()==39]

In [81]:

# save numpy array as npy file
from numpy import asarray
from numpy import save
# save to npy file
save('Data_09_lob_dist.npy', Data)

In [80]:
Data

                                시가       현재가      High    Low        매도총호가잔량  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90   12950.0  0.017992  0.019043  0.000   50380.016949
                      91   12950.0  0.023718  0.030888  0.000   64586.050420
                      92   12950.0  0.041475  0.047411  0.000   81665.257143
                      93   12950.0  0.038214  0.054054  0.000  117462.226107
                      94   12950.0  0.044530  0.054054  0.000  127686.404167
...                            ...       ...       ...    ...            ...
KR8392070007 20170907 144   6000.0 -0.019138  0.010000 -0.025   61946.827586
                      145   6000.0 -0.017546  0.010000 -0.025   63079.888889
                      150   6000.0 -0.021468  0.010000 -0.025   63610.000000
                      151   6000.0 -0.020556  0.010000 -0.025   62983.125000
                      152   6000.0 -0.022667  0.010000 -0.025   63651.400000

                                매수총호가잔량  ASK_STEP1_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90   46627.525424            1701.859564
                      91   53997.987395             949.672269
                      92   64156.687302            1567.811111
                      93   67493.312354             921.853147
                      94   74264.875000            2543.633333
...                                 ...                    ...
KR8392070007 20170907 144  25573.724138             526.068966
                      145  25556.000000             706.444444
                      150  24622.190476             394.619048
                      151  23223.166667             374.208333
                      152  22003.520000             859.560000

                           ASK_STEP2_BSTORD_RQTY  ASK_STEP3_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1936.694915            1553.389831
                      91             1262.609244            1589.857143
                      92             2127.057143            2754.607937
                      93             1886.431235            2860.261072
                      94             4339.054167            4927.541667
...                                          ...                    ...
KR8392070007 20170907 144            1129.103448            1274.689655
                      145            1305.722222            1371.666667
                      150             292.095238             944.952381
                      151             474.125000             998.541667
                      152             433.000000            1037.440000

                           ASK_STEP4_BSTORD_RQTY  ASK_STEP5_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1302.907990             966.075061
                      91             1464.331933            2529.155462
                      92             3217.973016            3261.119048
                      93             3708.081585            5036.403263
                      94             7944.412500            6293.783333
...                                          ...                    ...
KR8392070007 20170907 144             240.517241            1058.620690
                      145             437.777778            1182.833333
                      150            1378.714286            1007.190476
                      151            1128.041667             314.500000
                      152               0.000000               0.000000

                           BID_STEP1_BSTORD_RQTY  BID_STEP2_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90              979.355932             894.634383
                      91             1243.915966            1923.315126
                      92             1487.750794            1904.317460
                      93             1409.517483            2214.512821
                      94             2390.666667            3029.050000
...                                          ...                    ...
KR8392070007 20170907 144             459.172414            1228.896552
                      145              30.833333             277.388889
                      150             223.904762            1405.000000
                      151             351.583333             704.083333
                      152             470.920000             951.200000

                           BID_STEP3_BSTORD_RQTY  BID_STEP4_BSTORD_RQTY  \
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             1425.489104            2691.418886
                      91             2680.928571            2836.088235
                      92             2119.439683            1964.261905
                      93             2898.333333            3851.666667
                      94             2454.670833            2250.645833
...                                          ...                    ...
KR8392070007 20170907 144            1646.793103            1522.137931
                      145             722.388889            1099.055556
                      150            1865.666667            1014.047619
                      151             798.291667            1052.083333
                      152            1819.480000               0.000000

                           BID_STEP5_BSTORD_RQTY  ORD_QTY
ISU_CD       ORD_DD   hms
KR7000250001 20170901 90             2842.012107      0.0
                      91             2823.722689      0.0
                      92             2221.347619      0.0
                      93             3860.524476      0.0
                      94             4027.200000      0.0
...                                          ...      ...
KR8392070007 20170907 144             975.275862      0.0
                      145            1370.888889      0.0
                      150            1205.619048      0.0
                      151            1009.625000      0.0
                      152               0.000000      0.0

[174720 rows x 17 columns]

In [67]:
Data.groupby(['ISU_CD','ORD_DD']).size()

ISU_CD        ORD_DD
KR7000250001  20170901    5137
              20170904    7016
              20170905    3874
              20170906    2778
              20170907    3420
                          ...
KR8392070007  20170901    4334
              20170904    2657
              20170905    1549
              20170906    1302
              20170907    1164
Length: 4645, dtype: int64