In [1]:
import pandas as pd
import os
from source.TrainDataGeneration import append_ORD_TM,append_ORD_VOL,append_TM_GP,GetGroupDataFrame,append_STEP5
from DataInfo import ISU_list_MBRN_sum_top,MBRN_sum_top,header_df
from datetime import datetime

In [2]:

path_dir = '/Data/LOBData/CollectedRawData/MBRN_sum_top1516/'
# path_dir = '/Data/ksqord1516/'
# path_dir = '/Data/LOBData/CollectedTickData/MBRN1516/'
# ISUlist=ISU_list_MBRN_sum_top
a=os.listdir(path_dir)
a.sort()

In [3]:
header_df=['ISU_CD', 'ORD_DD', 'ORD_ACPT_NO', 'REGUL_OFFHR_TP_CD', 'BLKTRD_TP_CD', '호가장처리가격',
       'ASKBID_TP_CD', 'MODCANCL_TP_CD', 'ORD_TP_CD', 'ORD_COND_CD', 'INVST_TP_CD', 'ASK_STEP1_BSTORD_PRC',
       'ASK_STEP1_BSTORD_RQTY', 'ASK_STEP2_BSTORD_PRC','ASK_STEP2_BSTORD_RQTY','ASK_STEP3_BSTORD_PRC',
       'ASK_STEP3_BSTORD_RQTY','ASK_STEP4_BSTORD_PRC', 'ASK_STEP4_BSTORD_RQTY','ASK_STEP5_BSTORD_PRC',
       'ASK_STEP5_BSTORD_RQTY',
       'BID_STEP1_BSTORD_PRC', 'BID_STEP1_BSTORD_RQTY', 'BID_STEP2_BSTORD_PRC', 'BID_STEP2_BSTORD_RQTY',
       'BID_STEP3_BSTORD_PRC', 'BID_STEP3_BSTORD_RQTY','BID_STEP4_BSTORD_PRC', 'BID_STEP4_BSTORD_RQTY',
       'BID_STEP5_BSTORD_PRC', 'BID_STEP5_BSTORD_RQTY', 'ORD_ACPT_TM', 'ORD_QTY', 'ORD_PRC',
       '호가우선순위번호', 'MBR_NO', 'BRN_NO', 'CNTR_CD', 'TRST_PRINC_TP_CD', 'FORNINVST_TP_CD',
       'ORD_MEDIA_TP_CD', '회원사주문시각', '예상체결가격', '예상체결수량', '매도총호가잔량', '매수총호가잔량',
       '호가체결접수순서번호', '직전체결가격', '누적체결수량', '누적거래대금', 'AGG_TM', '시가', '고가', '저가',
       'ORGN_ORD_ACPT_NO', '시장구분코드', '자동취소처리구분코드', 'MKTSTAT_TP_CD', '매도10단계호가합계잔량',
       '매수10단계호가합계잔량', 'PT_TP_CD']

In [4]:
ISU_CD_list=[]
for filename in a[1:]:
    print(filename)
    Data=pd.read_csv(os.path.join(path_dir,filename))
    ISU_CD_list +=list(Data['ISU_CD'].value_counts().index) 
    ISU_CD_list = list(set(ISU_CD_list))

CollectedRawDataksqord_20150602.csv.csv
CollectedRawDataksqord_20150603.csv.csv
CollectedRawDataksqord_20150604.csv.csv

/root/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

CollectedRawDataksqord_20150605.csv.csv
CollectedRawDataksqord_20150608.csv.csv
CollectedRawDataksqord_20150609.csv.csv
CollectedRawDataksqord_20150610.csv.csv
CollectedRawDataksqord_20150611.csv.csv
CollectedRawDataksqord_20150612.csv.csv
CollectedRawDataksqord_20150615.csv.csv
CollectedRawDataksqord_20150616.csv.csv
CollectedRawDataksqord_20150617.csv.csv
CollectedRawDataksqord_20150618.csv.csv
CollectedRawDataksqord_20150619.csv.csv
CollectedRawDataksqord_20150622.csv.csv
CollectedRawDataksqord_20150623.csv.csv
CollectedRawDataksqord_20150624.csv.csv
CollectedRawDataksqord_20150625.csv.csv
CollectedRawDataksqord_20150626.csv.csv
CollectedRawDataksqord_20150629.csv.csv
CollectedRawDataksqord_20150630.csv.csv
CollectedRawDataksqord_20150701.csv.csv
CollectedRawDataksqord_20150702.csv.csv
CollectedRawDataksqord_20150703.csv.csv
CollectedRawDataksqord_20150706.csv.csv
CollectedRawDataksqord_20150707.csv.csv
CollectedRawDataksqord_20150708.csv.csv
CollectedRawDataksqord_20150709.csv.csv
CollectedRawDataksqord_20150710.csv.csv
CollectedRawDataksqord_20150713.csv.csv
CollectedRawDataksqord_20150714.csv.csv
CollectedRawDataksqord_20150715.csv.csv
CollectedRawDataksqord_20150716.csv.csv
CollectedRawDataksqord_20150717.csv.csv
CollectedRawDataksqord_20150720.csv.csv
CollectedRawDataksqord_20150721.csv.csv
CollectedRawDataksqord_20150722.csv.csv
CollectedRawDataksqord_20150723.csv.csv
CollectedRawDataksqord_20150724.csv.csv
CollectedRawDataksqord_20150727.csv.csv
CollectedRawDataksqord_20150728.csv.csv
CollectedRawDataksqord_20150729.csv.csv
CollectedRawDataksqord_20150730.csv.csv
CollectedRawDataksqord_20150731.csv.csv
CollectedRawDataksqord_20150803.csv.csv
CollectedRawDataksqord_20150804.csv.csv
CollectedRawDataksqord_20150805.csv.csv
CollectedRawDataksqord_20150806.csv.csv
CollectedRawDataksqord_20150807.csv.csv
CollectedRawDataksqord_20150810.csv.csv
CollectedRawDataksqord_20150811.csv.csv
CollectedRawDataksqord_20150812.csv.csv
CollectedRawDataksqord_20150813.csv.csv
CollectedRawDataksqord_20150817.csv.csv
CollectedRawDataksqord_20150818.csv.csv
CollectedRawDataksqord_20150819.csv.csv
CollectedRawDataksqord_20150820.csv.csv
CollectedRawDataksqord_20150821.csv.csv
CollectedRawDataksqord_20150824.csv.csv
CollectedRawDataksqord_20150825.csv.csv
CollectedRawDataksqord_20150826.csv.csv
CollectedRawDataksqord_20150827.csv.csv
CollectedRawDataksqord_20150828.csv.csv
CollectedRawDataksqord_20150831.csv.csv
CollectedRawDataksqord_20150901.csv.csv
CollectedRawDataksqord_20150902.csv.csv
CollectedRawDataksqord_20150903.csv.csv
CollectedRawDataksqord_20150904.csv.csv
CollectedRawDataksqord_20150907.csv.csv
CollectedRawDataksqord_20150908.csv.csv
CollectedRawDataksqord_20150909.csv.csv
CollectedRawDataksqord_20150910.csv.csv
CollectedRawDataksqord_20150911.csv.csv
CollectedRawDataksqord_20150914.csv.csv
CollectedRawDataksqord_20150915.csv.csv
CollectedRawDataksqord_20150916.csv.csv
CollectedRawDataksqord_20150917.csv.csv
CollectedRawDataksqord_20150918.csv.csv
CollectedRawDataksqord_20150921.csv.csv
CollectedRawDataksqord_20150922.csv.csv
CollectedRawDataksqord_20150923.csv.csv
CollectedRawDataksqord_20150924.csv.csv
CollectedRawDataksqord_20150925.csv.csv
CollectedRawDataksqord_20150930.csv.csv
CollectedRawDataksqord_20151001.csv.csv
CollectedRawDataksqord_20151002.csv.csv
CollectedRawDataksqord_20151005.csv.csv
CollectedRawDataksqord_20151006.csv.csv
CollectedRawDataksqord_20151007.csv.csv
CollectedRawDataksqord_20151008.csv.csv
CollectedRawDataksqord_20151012.csv.csv
CollectedRawDataksqord_20151013.csv.csv
CollectedRawDataksqord_20151014.csv.csv
CollectedRawDataksqord_20151015.csv.csv
CollectedRawDataksqord_20151016.csv.csv
CollectedRawDataksqord_20151019.csv.csv
CollectedRawDataksqord_20151020.csv.csv
CollectedRawDataksqord_20151021.csv.csv
CollectedRawDataksqord_20151022.csv.csv
CollectedRawDataksqord_20151023.csv.csv
CollectedRawDataksqord_20151026.csv.csv
CollectedRawDataksqord_20151027.csv.csv
CollectedRawDataksqord_20151028.csv.csv
CollectedRawDataksqord_20151029.csv.csv
CollectedRawDataksqord_20151030.csv.csv
CollectedRawDataksqord_20151102.csv.csv
CollectedRawDataksqord_20151103.csv.csv
CollectedRawDataksqord_20151104.csv.csv
CollectedRawDataksqord_20151105.csv.csv
CollectedRawDataksqord_20151106.csv.csv
CollectedRawDataksqord_20151109.csv.csv
CollectedRawDataksqord_20151110.csv.csv
CollectedRawDataksqord_20151111.csv.csv
CollectedRawDataksqord_20151112.csv.csv
CollectedRawDataksqord_20151113.csv.csv
CollectedRawDataksqord_20151116.csv.csv
CollectedRawDataksqord_20151117.csv.csv
CollectedRawDataksqord_20151118.csv.csv
CollectedRawDataksqord_20151119.csv.csv
CollectedRawDataksqord_20151120.csv.csv
CollectedRawDataksqord_20151123.csv.csv
CollectedRawDataksqord_20151124.csv.csv
CollectedRawDataksqord_20151125.csv.csv
CollectedRawDataksqord_20151126.csv.csv
CollectedRawDataksqord_20151127.csv.csv
CollectedRawDataksqord_20151130.csv.csv
CollectedRawDataksqord_20151201.csv.csv
CollectedRawDataksqord_20151202.csv.csv
CollectedRawDataksqord_20151203.csv.csv
CollectedRawDataksqord_20151204.csv.csv
CollectedRawDataksqord_20151207.csv.csv
CollectedRawDataksqord_20151208.csv.csv
CollectedRawDataksqord_20151209.csv.csv
CollectedRawDataksqord_20151210.csv.csv
CollectedRawDataksqord_20151211.csv.csv
CollectedRawDataksqord_20151214.csv.csv
CollectedRawDataksqord_20151215.csv.csv
CollectedRawDataksqord_20151216.csv.csv
CollectedRawDataksqord_20151217.csv.csv
CollectedRawDataksqord_20151218.csv.csv
CollectedRawDataksqord_20151221.csv.csv
CollectedRawDataksqord_20151222.csv.csv
CollectedRawDataksqord_20151223.csv.csv
CollectedRawDataksqord_20151224.csv.csv
CollectedRawDataksqord_20151228.csv.csv
CollectedRawDataksqord_20151229.csv.csv
CollectedRawDataksqord_20151230.csv.csv

In [5]:
ISU_CD_list

['KR7040670002',
 'KR7044180008',
 'KR7018700005',
 'KR7043200005',
 'KR7058820002',
 'KR7043100007',
 'KR7071930002',
 'KR7052420007',
 'KR7024810004',
 'KR7036540003']

In [6]:
len(ISU_CD_list)

10

In [7]:
groupmin=10
SaveDirPath='/Data/LOBData/CollectedTickData/ISUTickData1516/'
filename=a[0]
print(filename)
Data=pd.read_csv(os.path.join(path_dir,filename))    
for ISU_CD in ISU_CD_list:
    savename="GDF_tick"+"_"+ISU_CD+'_'+str(groupmin)+'.csv'
    Data[Data['ISU_CD']==ISU_CD].to_csv(SaveDirPath+savename,index=False)

for filename in a[1:]:
    print(filename)
    Data=pd.read_csv(os.path.join(path_dir,filename))    
    for ISU_CD in ISU_CD_list:
        savename="GDF_tick"+"_"+ISU_CD+'_'+str(groupmin)+'.csv'
        Data[Data['ISU_CD']==ISU_CD].to_csv(SaveDirPath+savename, mode='a', index=False, header=False)

CollectedRawDataksqord_20150601.csv.csv
CollectedRawDataksqord_20150602.csv.csv
CollectedRawDataksqord_20150603.csv.csv
CollectedRawDataksqord_20150604.csv.csv
CollectedRawDataksqord_20150605.csv.csv
CollectedRawDataksqord_20150608.csv.csv
CollectedRawDataksqord_20150609.csv.csv
CollectedRawDataksqord_20150610.csv.csv
CollectedRawDataksqord_20150611.csv.csv
CollectedRawDataksqord_20150612.csv.csv
CollectedRawDataksqord_20150615.csv.csv
CollectedRawDataksqord_20150616.csv.csv
CollectedRawDataksqord_20150617.csv.csv
CollectedRawDataksqord_20150618.csv.csv
CollectedRawDataksqord_20150619.csv.csv
CollectedRawDataksqord_20150622.csv.csv
CollectedRawDataksqord_20150623.csv.csv
CollectedRawDataksqord_20150624.csv.csv
CollectedRawDataksqord_20150625.csv.csv
CollectedRawDataksqord_20150626.csv.csv
CollectedRawDataksqord_20150629.csv.csv
CollectedRawDataksqord_20150630.csv.csv
CollectedRawDataksqord_20150701.csv.csv
CollectedRawDataksqord_20150702.csv.csv
CollectedRawDataksqord_20150703.csv.csv
CollectedRawDataksqord_20150706.csv.csv
CollectedRawDataksqord_20150707.csv.csv
CollectedRawDataksqord_20150708.csv.csv
CollectedRawDataksqord_20150709.csv.csv
CollectedRawDataksqord_20150710.csv.csv
CollectedRawDataksqord_20150713.csv.csv
CollectedRawDataksqord_20150714.csv.csv
CollectedRawDataksqord_20150715.csv.csv
CollectedRawDataksqord_20150716.csv.csv
CollectedRawDataksqord_20150717.csv.csv
CollectedRawDataksqord_20150720.csv.csv
CollectedRawDataksqord_20150721.csv.csv
CollectedRawDataksqord_20150722.csv.csv
CollectedRawDataksqord_20150723.csv.csv
CollectedRawDataksqord_20150724.csv.csv
CollectedRawDataksqord_20150727.csv.csv
CollectedRawDataksqord_20150728.csv.csv
CollectedRawDataksqord_20150729.csv.csv
CollectedRawDataksqord_20150730.csv.csv
CollectedRawDataksqord_20150731.csv.csv
CollectedRawDataksqord_20150803.csv.csv
CollectedRawDataksqord_20150804.csv.csv
CollectedRawDataksqord_20150805.csv.csv
CollectedRawDataksqord_20150806.csv.csv
CollectedRawDataksqord_20150807.csv.csv
CollectedRawDataksqord_20150810.csv.csv
CollectedRawDataksqord_20150811.csv.csv
CollectedRawDataksqord_20150812.csv.csv
CollectedRawDataksqord_20150813.csv.csv
CollectedRawDataksqord_20150817.csv.csv
CollectedRawDataksqord_20150818.csv.csv
CollectedRawDataksqord_20150819.csv.csv
CollectedRawDataksqord_20150820.csv.csv
CollectedRawDataksqord_20150821.csv.csv
CollectedRawDataksqord_20150824.csv.csv
CollectedRawDataksqord_20150825.csv.csv
CollectedRawDataksqord_20150826.csv.csv
CollectedRawDataksqord_20150827.csv.csv
CollectedRawDataksqord_20150828.csv.csv
CollectedRawDataksqord_20150831.csv.csv
CollectedRawDataksqord_20150901.csv.csv
CollectedRawDataksqord_20150902.csv.csv
CollectedRawDataksqord_20150903.csv.csv
CollectedRawDataksqord_20150904.csv.csv
CollectedRawDataksqord_20150907.csv.csv
CollectedRawDataksqord_20150908.csv.csv
CollectedRawDataksqord_20150909.csv.csv
CollectedRawDataksqord_20150910.csv.csv
CollectedRawDataksqord_20150911.csv.csv
CollectedRawDataksqord_20150914.csv.csv
CollectedRawDataksqord_20150915.csv.csv
CollectedRawDataksqord_20150916.csv.csv
CollectedRawDataksqord_20150917.csv.csv
CollectedRawDataksqord_20150918.csv.csv
CollectedRawDataksqord_20150921.csv.csv
CollectedRawDataksqord_20150922.csv.csv
CollectedRawDataksqord_20150923.csv.csv
CollectedRawDataksqord_20150924.csv.csv
CollectedRawDataksqord_20150925.csv.csv
CollectedRawDataksqord_20150930.csv.csv
CollectedRawDataksqord_20151001.csv.csv
CollectedRawDataksqord_20151002.csv.csv
CollectedRawDataksqord_20151005.csv.csv
CollectedRawDataksqord_20151006.csv.csv
CollectedRawDataksqord_20151007.csv.csv
CollectedRawDataksqord_20151008.csv.csv
CollectedRawDataksqord_20151012.csv.csv
CollectedRawDataksqord_20151013.csv.csv
CollectedRawDataksqord_20151014.csv.csv
CollectedRawDataksqord_20151015.csv.csv
CollectedRawDataksqord_20151016.csv.csv
CollectedRawDataksqord_20151019.csv.csv
CollectedRawDataksqord_20151020.csv.csv
CollectedRawDataksqord_20151021.csv.csv
CollectedRawDataksqord_20151022.csv.csv
CollectedRawDataksqord_20151023.csv.csv
CollectedRawDataksqord_20151026.csv.csv
CollectedRawDataksqord_20151027.csv.csv
CollectedRawDataksqord_20151028.csv.csv
CollectedRawDataksqord_20151029.csv.csv
CollectedRawDataksqord_20151030.csv.csv
CollectedRawDataksqord_20151102.csv.csv
CollectedRawDataksqord_20151103.csv.csv
CollectedRawDataksqord_20151104.csv.csv
CollectedRawDataksqord_20151105.csv.csv
CollectedRawDataksqord_20151106.csv.csv
CollectedRawDataksqord_20151109.csv.csv
CollectedRawDataksqord_20151110.csv.csv
CollectedRawDataksqord_20151111.csv.csv
CollectedRawDataksqord_20151112.csv.csv
CollectedRawDataksqord_20151113.csv.csv
CollectedRawDataksqord_20151116.csv.csv
CollectedRawDataksqord_20151117.csv.csv
CollectedRawDataksqord_20151118.csv.csv
CollectedRawDataksqord_20151119.csv.csv
CollectedRawDataksqord_20151120.csv.csv
CollectedRawDataksqord_20151123.csv.csv
CollectedRawDataksqord_20151124.csv.csv
CollectedRawDataksqord_20151125.csv.csv
CollectedRawDataksqord_20151126.csv.csv
CollectedRawDataksqord_20151127.csv.csv
CollectedRawDataksqord_20151130.csv.csv
CollectedRawDataksqord_20151201.csv.csv
CollectedRawDataksqord_20151202.csv.csv
CollectedRawDataksqord_20151203.csv.csv
CollectedRawDataksqord_20151204.csv.csv
CollectedRawDataksqord_20151207.csv.csv
CollectedRawDataksqord_20151208.csv.csv
CollectedRawDataksqord_20151209.csv.csv
CollectedRawDataksqord_20151210.csv.csv
CollectedRawDataksqord_20151211.csv.csv
CollectedRawDataksqord_20151214.csv.csv
CollectedRawDataksqord_20151215.csv.csv
CollectedRawDataksqord_20151216.csv.csv
CollectedRawDataksqord_20151217.csv.csv
CollectedRawDataksqord_20151218.csv.csv
CollectedRawDataksqord_20151221.csv.csv
CollectedRawDataksqord_20151222.csv.csv
CollectedRawDataksqord_20151223.csv.csv
CollectedRawDataksqord_20151224.csv.csv
CollectedRawDataksqord_20151228.csv.csv
CollectedRawDataksqord_20151229.csv.csv
CollectedRawDataksqord_20151230.csv.csv

for filename in a[2:]:
    print(filename)
    Data=pd.read_csv(os.path.join(path_dir,filename))   
    Data=append_ORD_TM(Data)
    Data=append_ORD_VOL(Data)
    Data=append_TM_GP(Data,groupmin=groupmin)
    Data=append_STEP5(Data)
    for ISU_CD in ISU_CD_list:
        savename="GDF_tick"+"_"+ISU_CD+'_'+str(groupmin)+'.csv'
        Data[Data['ISU_CD']==ISU_CD].to_csv(SaveDirPath+savename, mode='a', index=False, header=False)

In [8]:
Data[Data['ISU_CD']==ISU_CD]

,Unnamed: 0,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,...,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD
478,1192645,KR7036540003,20151230,3,1,0,2730,1,1,2,...,2435,2435,2435,0,2,0,10,0,0,0
479,1192671,KR7036540003,20151230,29,1,0,2435,2,1,2,...,2435,2435,2435,0,2,0,10,0,0,0
480,1192687,KR7036540003,20151230,45,1,0,2200,2,1,2,...,2435,2435,2435,0,2,0,10,0,0,0
481,1192706,KR7036540003,20151230,64,1,0,2880,1,1,2,...,2435,2435,2435,0,2,0,10,0,0,0
482,1192727,KR7036540003,20151230,84,1,0,2620,1,1,2,...,2435,2435,2435,0,2,0,10,1192,304,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1357,1196174,KR7036540003,20151230,23,4,0,2310,2,1,2,...,2470,2470,2420,0,2,0,70,1212,2643,0
1358,1196182,KR7036540003,20151230,31,4,0,2350,2,1,2,...,0,2460,2460,0,2,0,70,1412,2005,0
1359,1196189,KR7036540003,20151230,38,4,0,2400,2,1,2,...,0,2460,2460,0,2,0,70,2412,2004,0
1360,1196203,KR7036540003,20151230,52,4,0,2410,2,1,2,...,0,2460,2460,0,2,0,70,2174,2569,0
1361,1196221,KR7036540003,20151230,70,4,0,2470,1,1,2,...,0,2460,2455,0,2,0,70,8301,2542,0

In [9]:
data=pd.read_csv(SaveDirPath+savename)

/root/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [10]:
data

,Unnamed: 0,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,...,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD
0,1685973,KR7036540003,20150601,4,2,0,4905,2,1,2,...,4905,4905,4905,0,2,0,50,0,2780,0
1,1685974,KR7036540003,20150601,5,2,0,4905,2,1,2,...,4905,4905,4905,0,2,0,50,0,2880,0
2,1685975,KR7036540003,20150601,6,2,0,4905,1,1,2,...,4905,4905,4905,0,2,0,50,0,2880,0
3,1685976,KR7036540003,20150601,7,2,0,4905,2,1,2,...,0,4905,4905,0,2,0,50,0,1380,0
4,1685980,KR7036540003,20150601,11,2,0,4905,2,1,2,...,0,4905,4905,0,2,0,50,0,3680,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374169,1196174,KR7036540003,20151230,23,4,0,2310,2,1,2,...,2470,2470,2420,0,2,0,70,1212,2643,0
374170,1196182,KR7036540003,20151230,31,4,0,2350,2,1,2,...,0,2460,2460,0,2,0,70,1412,2005,0
374171,1196189,KR7036540003,20151230,38,4,0,2400,2,1,2,...,0,2460,2460,0,2,0,70,2412,2004,0
374172,1196203,KR7036540003,20151230,52,4,0,2410,2,1,2,...,0,2460,2460,0,2,0,70,2174,2569,0
374173,1196221,KR7036540003,20151230,70,4,0,2470,1,1,2,...,0,2460,2455,0,2,0,70,8301,2542,0

for ISU_CD in ISU_CD_list:
    print(SaveDirPath+savename)
    GDF.to_csv(SaveDirPath+savename)
    with open(SaveDirPath+'DataInformation.txt', "a+") as f:
        f.write(savename+'\t'+path_dir+'\n')
        f.write(str(groupmin)+'\n')
        for col in groupcolumns:
            f.write(str(col)+'\t')
        f.write('\n')

In [11]:
Data

,Unnamed: 0,ISU_CD,ORD_DD,ORD_ACPT_NO,REGUL_OFFHR_TP_CD,BLKTRD_TP_CD,호가장처리가격,ASKBID_TP_CD,MODCANCL_TP_CD,ORD_TP_CD,...,시가,고가,저가,ORGN_ORD_ACPT_NO,시장구분코드,자동취소처리구분코드,MKTSTAT_TP_CD,매도10단계호가합계잔량,매수10단계호가합계잔량,PT_TP_CD
0,448226,KR7018700005,20151230,5,1,0,3070,1,1,2,...,2990,2990,2990,0,2,0,10,0,0,0
1,448227,KR7018700005,20151230,6,1,0,2785,2,1,2,...,2990,2990,2990,0,2,0,10,0,0,0
2,448228,KR7018700005,20151230,7,1,0,2525,2,1,2,...,2990,2990,2990,0,2,0,10,0,0,0
3,448229,KR7018700005,20151230,8,1,0,3385,1,1,2,...,2990,2990,2990,0,2,0,10,0,0,0
4,448230,KR7018700005,20151230,9,1,0,3735,1,1,2,...,2990,2990,2990,0,2,0,10,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8962,3093759,KR7058820002,20151230,98,4,0,2115,1,1,2,...,0,2115,2100,0,2,0,70,130,2291,0
8963,3093761,KR7058820002,20151230,100,4,0,2100,2,1,2,...,0,2115,2100,0,2,0,70,121,2391,0
8964,3093764,KR7058820002,20151230,103,4,0,2110,1,1,2,...,0,2115,2100,0,2,0,70,130,1938,0
8965,3093765,KR7058820002,20151230,104,4,0,2100,2,1,2,...,0,2115,2100,0,2,0,70,130,2038,0
8966,3093767,KR7058820002,20151230,106,4,0,2110,1,3,2,...,0,2115,2100,103,2,0,70,121,1790,0

In [12]:
for filename in a:
    Data=pd.read_csv(os.path.join(path_dir,filename))
    Data=append_ORD_TM(Data)
    Data=append_ORD_VOL(Data)
    Data=append_TM_GP(Data,groupmin=groupmin)
    Data=append_STEP5(Data)
    GDF=GetGroupDataFrame(Data,groupcolumns,sumcolumns,meancolumns,lastcolumns)
    SaveDirPath='/Data/LOBData/CollectedTickData/MBRN1516/'
    now=datetime.now()
    savename="GDF_tick"+"_"+filename+'_'+str(groupmin)+'_'+str(now.month)+'_'+str(now.day)+'.csv'
    print(SaveDirPath+savename)
    GDF.to_csv(SaveDirPath+savename)
    with open(SaveDirPath+'DataInformation.txt', "a+") as f:
        f.write(savename+'\t'+path_dir+'\n')
        f.write(str(groupmin)+'\n')
        for col in groupcolumns:
            f.write(str(col)+'\t')
        f.write('\n')

NameError: name 'groupcolumns' is not defined

In [ ]:
GDF

In [ ]:
bbb

In [ ]:
filename=a[1]
Data1=pd.read_csv(os.path.join(path_dir,filename))
Data=append_ORD_TM(Data1)
Data=append_ORD_VOL(Data)
Data=append_TM_GP(Data,groupmin=groupmin)
Data=append_STEP5(Data)
GDF=GetGroupDataFrame(Data,groupcolumns,sumcolumns,meancolumns,lastcolumns)
for filename in a[2:]:
    Data1=pd.read_csv(os.path.join(path_dir,filename))
    Data=append_ORD_TM(Data1)
    Data=append_ORD_VOL(Data)
    Data=append_TM_GP(Data,groupmin=groupmin)
    Data=append_STEP5(Data)
    TGDF=GetGroupDataFrame(Data,groupcolumns,sumcolumns,meancolumns,lastcolumns)
    GDF=pd.concat([GDF,TGDF])

In [ ]:
a[1]

Data1=pd.read_csv('CollectedData/2022_3_20_22_25.csv')
Data=append_ORD_TM(Data1)
Data=append_ORD_VOL(Data)
Data=append_TM_GP(Data,groupmin=groupmin)
Data=append_STEP5(Data)
GDF2=GetGroupDataFrame(Data,groupcolumns,sumcolumns,meancolumns,lastcolumns)

Data1=pd.read_csv('CollectedData/2022_3_20_22_33.csv')
Data=append_ORD_TM(Data1)
Data=append_ORD_VOL(Data)
Data=append_TM_GP(Data,groupmin=groupmin)
Data=append_STEP5(Data)
GDF3=GetGroupDataFrame(Data,groupcolumns,sumcolumns,meancolumns,lastcolumns)

In [ ]:
GDF['TM_GP'].max()

In [ ]:
GDF.head(20)

GDF=pd.concat([GDF1,GDF2,GDF3])

In [ ]:
from datetime import datetime

In [ ]:
SaveDirPath='/Data/LOBData/CollectedTickData/'
now=datetime.now()
filename="GDF"+str(now.year)+'_'+str(now.month)+'_'+str(now.day)+'_'+str(now.hour)+'_'+str(now.minute)+'.csv'
print(SaveDirPath+filename)
GDF.to_csv(SaveDirPath+filename)

a=[]